### ISSUE TITLE
Possible to get list of postseason games?

### ISSUE THREAD

**Issue by Kirkman** [BurntSushi/nflgame#106]
If I'm understanding the API documentation, I should be able to do this to get a list of games for the first week of this year's playoffs:

    games = nflgame.games(2014, week=1, kind='POST')

However, when I try to do this, Python errors out with:
```
  File "/sbbs/xtrn/sportsstats/nfl.py", line 131, in parseSchedule
    games = nflgame.games(year, week=theweek, kind=season)
  File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 219, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
```

This code works just fine for regular season games. I'm only getting errors when I switch to postseason. Am I doing something wrong, or is this a problem on nflgame's side?

**Comment by rjhaz** [comment]
If I had to guess, I would say week 18.

**Comment by Kirkman** [comment]
@rjhaz, thanks for the reply. Same result if you put '18'. But in any case, the [API docs](http://pdoc.burntsushi.net/nflgame#nflgame.games) are pretty clear that the week numbers begin with 1 for each season type. So, first week of playoffs is 1. 

I think the problem is deeper. My ```schedule.json``` file doesn't have any 2014 postseason games in it.

**Comment by ochawkeye** [comment]
You can run the schedule script found in your Lib/site-packages/nflgame
folder to update your JSON schedule file though I'm not convinced it will
solve your problem as I'm seeing an empty set despite finding 2014 playoff
games in my file.

**Comment by BurntSushi** [comment]
I've pushed an update and made a new release on PyPI (version: `1.2.10`). If you update your `nflgame`, the error should be fixed.

However, it does return an empty list because the `nflgame` API only deals with games that have been played or *are* being played. If you want a higher level interface, you can use `nfldb`. Or, if you just want to hack at the schedule, you can use the `nflgame.sched.games` variable documented here: https://github.com/BurntSushi/nflgame/blob/master/nflgame/sched.py#L48

**Comment by BurntSushi** [comment]
As we move through the post-season, I'll continue to update `nflgame` with schedule updates. So to stay current, you just need to update `nflgame`.

However, if I drop the ball or am not moving fast enough for you, then you can update the schedule yourself with this command:

```
nflgame-update-schedule --phase POST --year 2014 --week 1
```

Of course, you'll want to change the `--week` parameter.

**Comment by BurntSushi** [comment]
For those using `nfldb`, I've just pushed an update `0.2.9` there too. If you `pip install --upgrade nfldb`, then you should automatically get the updated playoff schedule the next time you run `nfldb-update`.

**Comment by Kirkman** [comment]
Thanks, @BurntSushi!  One followup question: How can I find out programmatically what season phase I'm in? I am using ```nflgame.live.current_year_and_week()```, but it doesn't return 'REG' or 'POST'.

**Comment by BurntSushi** [comment]
Hmm. Good question. I'd probably just do this:

```python
nflgame.live._update_week_number()
print nflgame.live._cur_season_phase
```

[This is how it's done in `nfldb-update`.](https://github.com/BurntSushi/nfldb/blob/master/nfldb/update.py#L111-L116)

**Comment by Kirkman** [comment]
Sweet, thanks!  Maybe for the future it might be worth considering adding a method like nflgame.live.current_phase().
