### ISSUE TITLE
Missing Extra Point / 2pt Conv Plays After Defensive Touchdowns

### ISSUE THREAD

**Issue by krusta80** [BurntSushi/nflgame#112]
I'm not sure whether this is due to the code or the NFL feed itself, but I have yet to find a game containing an extra point or 2-point conversion play after a defensive TOUCHDOWN (ie. a pick six).  The next play returned seems to always be a kick off in such cases.

I found this to be true for both interceptions and fumble recoveries resulting in an immediate touchdown.

At first I thought that maybe the assumption is a made XP unless otherwise noted, but then I found an example of a defensive TD, followed by a 2-pt conversion (week 13 in 2012 - SF vs. STL) that also went unreported by nflgame. 

This obviously makes it impossible to keep track of the score of the game with 100% accuracy.

**Comment by ochawkeye** [comment]
Yeah.  Unfortunately, the blame goes entirely to the source data from nfl.com

From nfl.com play-by-plays:
Week 17 2014 - Carolina @ Atlanta
```
2-20-ATL 9
(4:32) (Shotgun) 2-M.Ryan pass deep right intended for 84-R.White INTERCEPTED by 41-R.Harper [95-C.Johnson] at ATL 31. 41-R.Harper for 31 yards, TOUCHDOWN.
Atlanta Falcons at 04:18
9-G.Gano kicks 71 yards from CAR 35 to ATL -6. 17-D.Hester to ATL 23 for 29 yards (33-T.Boston). PENALTY on ATL-53-P.Shembo, Offensive Holding, 6 yards, enforced at ATL 12.
```

Week 12 2012 - San Francisco @ St. Louis
```
3-3-SF 17
(3:11) (Shotgun) 7-C.Kaepernick FUMBLES (Aborted) at SF 12, RECOVERED by STL-21-J.Jenkins at SF 2. 21-J.Jenkins for 2 yards, TOUCHDOWN. The Replay Assistant challenged the backward pass ruling, and the play was Upheld.
San Francisco 49ers at 03:04
4-G.Zuerlein kicks 73 yards from STL 35 to SF -8. 19-T.Ginn, Touchback.
```

This is the first I have noticed that it is always defensive touchdowns that are missing extra point play-by-play information.  

FYI - `nfldb` does offer a `score_at_time` function that would deliver to you the score at any particular point in the game. (See https://github.com/BurntSushi/nfldb/issues/6)

**Comment by krusta80** [comment]
Thanks for the lightening-quick reply.  I will have my code check for a
defensive touchdown and then use the score_at_time function to update the
score if need be.

**Comment by ochawkeye** [comment]
There are a number of `nflgame`-specific methods to arrive at the score as well.

`Game` `score_home` and `score_away` might be of use.

During completed games those are aware of the actual score despite play-by-play not being able to arrive at those totals.  While games are being played this holds true as well.

```python
    games = nflgame.games(2014, 17)
    for game in games:
            print game.nice_score()
            print game.home, game.score_home, game.away, game.score_away
```

```
CAR (34) at ATL (3)
ATL 3 CAR 34
CLE (10) at BAL (20)
BAL 20 CLE 10
DET (20) at GB (30)
GB 30 DET 20
JAC (17) at HOU (23)
HOU 23 JAC 17
SD (7) at KC (19)
KC 19 SD 7
NYJ (37) at MIA (24)
MIA 24 NYJ 37
CHI (9) at MIN (13)
MIN 13 CHI 9
BUF (17) at NE (9)
NE 9 BUF 17
PHI (34) at NYG (26)
NYG 26 PHI 34
CIN (17) at PIT (27)
PIT 27 CIN 17
NO (23) at TB (20)
TB 20 NO 23
IND (27) at TEN (10)
TEN 10 IND 27
DAL (44) at WAS (17)
WAS 17 DAL 44
OAK (14) at DEN (47)
DEN 47 OAK 14
ARI (17) at SF (20)
SF 20 ARI 17
STL (6) at SEA (20)
SEA 20 STL 6
```

**Comment by krusta80** [comment]
That sounds great; I'll give it a whirl tonight.

Thanks again!

--John

**Comment by krusta80** [comment]
One more quick question...would you say I'm safe polling for new plays
every 10 seconds today?  I figure it's enough to be under the radar, but
obviously you know best.

**Comment by ochawkeye** [comment]
The Game Center page on NFL.com is only updated evey 15 seconds (according to [live.py](https://github.com/BurntSushi/nflgame/blob/master/nflgame/live.py#L192)) so anything more often than that won't buy to much.

**Comment by krusta80** [comment]
Gotcha...enjoy the game!  Thanks again.

**Comment by krusta80** [comment]
Today's game is week 5 in nflgame.  Is that correct?  The past few years'
games were week 4's.  Sorry to be a pain, but I want to make sure I am
reading the correct feed.  lol

**Comment by ochawkeye** [comment]
That is a fine question.  According to `nflgame.live.current_year_and_week()` it is indeed (2014, 5) and you are correct that in years past the Super Bowl was week 4 despite a Pro Bowl sneaking in there between the Conference Championship & Super Bowl.  It's possible @BurntSushi made an adjustment to move those previous Super Bowls into week 4?

**Comment by ochawkeye** [comment]
Week 5 does indeed appear to be the week.  Not sure if that is the intent, but I can't imagine much downside other than having some difficulty in comparing Super Bowls from season to season.

```python
import nflgame
print [str(g) for g in nflgame.games(2014, 5, kind='POST')]
```
```
['NE (0) at SEA (0)']
```

**Comment by krusta80** [comment]
Sounds good.  I just wanted to confirm that's all

**Comment by krusta80** [comment]
Just in case you were curious, here's a link to what I was working on:
http://pandora.dyndns.biz/boxes

I had a lot of free time the past two weeks.  :)

PS - Please excuse any horrendous code you may come across; I really hacked
it together.  lol

**Comment by BurntSushi** [comment]
@krusta80 That's awesome! I've added it to the wiki. :-) https://github.com/BurntSushi/nflgame/wiki/How-do-people-use-nflgame%3F

**Comment by krusta80** [comment]
Hey there!  Just wondering if/when to expect the list of this season's
games to be available?  :)

**Comment by BurntSushi** [comment]
@krusta80 It's been available for quite some time. Make sure you're running the latest nflgame. i.e., `pip install --upgrade nflgame`.

**Comment by krusta80** [comment]
That did it!  Sorry, this is my first second season with nflgame.  ;)

**Comment by krusta80** [comment]
I suppose that was redundant...first non-first season.  Wow, I need some
coffee stat.

Thanks again!

**Comment by BurntSushi** [comment]
:-)
