### ISSUE TITLE
Super Bowl 

### ISSUE THREAD

**Issue by tmarkwell16** [BurntSushi/nflgame#114]
When I try to pull the super bowl data from super bowl 49 it echos none. How can I fix this?
![nflgame](https://cloud.githubusercontent.com/assets/11262748/6479653/25329924-c206-11e4-938a-ce548a08ec6a.PNG)

**Comment by leighlondon** [comment]
You need to change it from:

```
x = nflgame.one(2014, 4, "SEA", "NE")
```

to:

```
x = nflgame.one(2014, 5, "SEA", "NE", kind="POST")
```

**Comment by tmarkwell16** [comment]
Thank you!

**Comment by tmarkwell16** [comment]
Well this is odd.... it worked on my debian VM... but on my raspberry pi it doesn't work
![nflgame1](https://cloud.githubusercontent.com/assets/11262748/6568468/917003ce-c69d-11e4-9aa1-e20c904eb750.PNG)

**Comment by tmarkwell16** [comment]
Normal games work...
![nflgame2](https://cloud.githubusercontent.com/assets/11262748/6568516/4ac9109a-c69e-11e4-9afe-59962e9ae718.PNG)

**Comment by ochawkeye** [comment]
What version of `nflgame` do you have running on your Pi?
![image](https://cloud.githubusercontent.com/assets/2996205/6569559/7c92c3a2-c6ba-11e4-9bf5-77481cafca84.png)

**Comment by leighlondon** [comment]
Does a week 17 game from the 2014 season work? Or a different playoff game from the 2014 season?

**Comment by tmarkwell16** [comment]
Here is my version:
![nflgame3](https://cloud.githubusercontent.com/assets/11262748/6588268/d8d0458c-c754-11e4-9136-e7f82baad8fa.PNG)

**Comment by tmarkwell16** [comment]
2014 season works
![nflgame4](https://cloud.githubusercontent.com/assets/11262748/6588342/da62f880-c755-11e4-8209-ab4140b8bd0f.PNG)

**Comment by BurntSushi** [comment]
I'm not sure what's wrong. Does your Raspberry Pi have Internet access? Some of the games might not be in the distribution yet.

**Comment by tmarkwell16** [comment]
yes, it has internet access and raspbian was installed and updated right before I installed nflgame

**Comment by BurntSushi** [comment]
@tmarkwell16 I don't know what's wrong then. If you have an Internet connection, you should get the latest games. I'm uploading a new release of `nflgame` now, which includes the latest schedule/player/game updates. Try upgrading (and make sure you get the new `1.2.14` version installed):

```
(nfl)[andrew@Liger ~] pip install --upgrade nflgame
(nfl)[andrew@Liger ~] pip list | grep nflgame
nflgame (1.2.14)
```

**Comment by ochawkeye** [comment]
I'm actually seeing the same thing in a fresh Linux install.
![screenshot - 110315 - 143119](https://cloud.githubusercontent.com/assets/2996205/6598402/6032f794-c7fb-11e4-8c72-c2584c81128c.png)

**Comment by BurntSushi** [comment]
@ochawkeye Try upgrading `nflgame`?

**Comment by ochawkeye** [comment]
Sure, sure.  That works.  But why is it not pulling games that weren't included with the release?

**Comment by BurntSushi** [comment]
Hmm, not sure. I tried it on my machine (in a fresh install) and it seemed to work OK. To know more, I'd have to reproduce the issue and figure out where things were going wrong.

Usually, this is because the schedule isn't updated to know about the game requested, so it doesn't know where to look.

**Comment by tmarkwell16** [comment]
I can send you my raspberry pi's image file.

**Comment by ochawkeye** [comment]
Maybe a write permissions issue for the storing of the newer game JSON files?  I've tried poking and prodding to locate those but can't even find my site-packages (Linux noob!).  Although now that I've updated my box to `1.2.14` that ship might have sailed for that guy until next preseason anyway...

**Comment by BurntSushi** [comment]
@tmarkwell16 Did you upgrade `nflgame`?

**Comment by BurntSushi** [comment]
@ochawkeye In theory, if there is a write permissions error, `nflgame` will yell at you.

**Comment by tmarkwell16** [comment]
I have not updated nflgame yet... I'm at work and can't  ssh my pi

**Comment by tmarkwell16** [comment]
Works now! Thank all of you!
![nflgame5](https://cloud.githubusercontent.com/assets/11262748/6609553/b10507e4-c818-11e4-8468-d920cd20dbd1.PNG)
