### ISSUE TITLE
Getting Bye Weeks from nflgame.sched.games

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#118]
Is there a way to get Bye weeks?

**Comment by rjhaz** [comment]
I have a PHP program that gets the schedule and the byes (derived by a team’s absence in the week’s schedule).  Send me an email to ray@raysffl.com if you want an example.  If you want to stick with Python then you would just do the same bye added it to the Python schedule program.


Ray

**Comment by BurntSushi** [comment]
There isn't a convenient API for it, no. But certainly, the data is there. You'll probably want to scan [the raw schedule](https://github.com/BurntSushi/nflgame/blob/master/nflgame/sched.py#L47-L49) and figure out the bye weeks manually.
