### ISSUE TITLE
NFL 2015 Schedule

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#119]
I noticed that NFL.com updated the 2015 Schedule.  I ran nflgame.update_players.run(), but the json does not contain 2015.  Is there something that needs to occur on the script to pull 2015?

**Comment by BurntSushi** [comment]
You probably need to run `nflgame-update-schedule`.

Note that things can be pretty screwy during the offseason, especially this early on.

**Comment by mesee298** [comment]
Maybe I'm not understanding something correctly.  I have ran nflgame-update-schedule, but it still only shows 2014.  But if I go to (for example) http://www.nfl.com/ajax/scorestrip?season=2015&seasonType=REG&week=15 it shows data.  I'm not that proficient in Python, but is it because the "nflgame.live" function is not looking for a 2015?

**Comment by BurntSushi** [comment]
When running programs on the command line that you aren't familiar with, you should run them with `{cmd} --help`. Usually `--help` will show you how to use the command.

In this case, there is a `--year` flag that you can pass.

If that still doesn't work, please provide more details on exactly what command you ran.

**Comment by mesee298** [comment]
Here is a test that I ran:
"update_sched.py --year 2015 --phase REG --week 1 --rebuild"

And you can see by the examples output of schedule.json is start with 2009 and goes to the 2014 super bowl:

![image](https://cloud.githubusercontent.com/assets/7937843/7521296/667c57ce-f4b2-11e4-8bf9-d33112f13b29.png)

![image](https://cloud.githubusercontent.com/assets/7937843/7521315/91d37d3a-f4b2-11e4-8f0a-a3a2d3a5fc69.png)

**Comment by mesee298** [comment]
Any thoughts BurntSushi?

**Comment by BurntSushi** [comment]
@mesee298 Sorry about the tardiness, but I think this is fixed. I've updated the schedule to include the 2015 season. If you run `pip install --upgrade nflgame` you should get it automatically. (Make sure you have version `1.2.15`.)
