### ISSUE TITLE
player.all_stats() raises an AttributeError

### ISSUE THREAD

**Issue by Exnihilation** [BurntSushi/nflgame#122]
Input:

```python
import nflgame

g = nflgame.one(2011, 17, "NE", "BUF")
p = g.players.name("T.Brady")
p.all_stats()
```
Output:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-6b35286b6c94> in <module>()
----> 1 p.all_stats()

/usr/lib/python2.7/site-packages/nflgame/player.pyc in __getattr__(self, name)
    304             if name.startswith(cat):
    305                 return 0
--> 306         raise AttributeError
    307
    308     def passer_rating(self):

AttributeError:
```

In order to rule out this error being specific to a particular case, I've tried this with several different players in several different games across the 2011-2014 NFL seasons with the same results.

Thanks

**Comment by ochawkeye** [comment]
Is `all_stats()` a real thing?  This gives same error:

```python
import nflgame

g = nflgame.one(2011, 17, "NE", "BUF")

p = g.players.name("T.Brady")
print p, p.passing_yds

print p.fake_attribute
```
```
T.Brady 338
Traceback (most recent call last):
  File "exnihilation.py", line 8, in <module>
    print p.fake_attribute
  File "D:\Python27\lib\site-packages\nflgame\player.py", line 306, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by ochawkeye** [comment]
I edited my response to include `p.stats` and `p.formatted_stats()` information, but if you're only seeing this over email my original comment might not have been very helpful :)

**Comment by Exnihilation** [comment]
After delving into the API, I'm not so sure "all_stats" is a thing after all. However, it is referenced in the wiki here: https://github.com/BurntSushi/nflgame/wiki/Tutorial-for-non-programmers:-Installation-and-examples#getting-a-particular-players-statistics

>In this example, we load a player into the aptly named tom_brady variable. We then print the player's name and a roughly formatted list of all statistics available for the player in this particular game. The formatted statistics are accessed with the formatted_stats method, which works on every player. **(There is also an all_stats method that returns a dictionary of statistics.)**

**Comment by ochawkeye** [comment]
Ah - gotcha.  Yeah, @BurntSushi did a pretty major code overhaul about a month after the wiki was written.  The `all_stats()` method was replaced by `stats` at that time.
[Major reorganization. Play by play data. Game diffing.](https://github.com/BurntSushi/nflgame/commit/b2c99680bd96723f922ef78f513944762ba8f302#diff-f2b70e3d43056e9d16fb0fa762521c32L301)
