### ISSUE TITLE
incorrect stats

### ISSUE THREAD

**Issue by linkinpaak** [BurntSushi/nflgame#125]
It seems like games where a player accrues no stats are excluded from the player's game logs.  For instance, A.J. Green played 13 games last year, but had 2 games last year where he had no catches, week 2 he started the game and got pulled very early without even registering a target and week 16 he played hurt and had no catches but still had 4 targets.  Neither of these games are counted when you execute the following (output is 11):

import nflgame

players = nflgame.players

for p in players:
	if players[p].full_name=='A.J. Green':
		print players[p].stats(2014).games

I also noticed that if I try and extract game logs for each week - nflgame.combine(nflgame.games(2014, week=2)).csv('C:\2014_week_2.csv') - he does not appear in the ouput file and the same goes for week 16.

**Comment by BurntSushi** [comment]
This is a fundamental limitation of data from NFL.com. It's unfortunate, but the data only tracks players that record statistics. (Try doing analysis on offensive linemen, for example, it's basically impossible.)
