### ISSUE TITLE
p.players.position error with nonetype

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#129]
I'm trying to do a "for p in players" (players = nflgame.combine_max_stats(games)), but because the NFL rosters is still fluid I'm getting a "AttributeError: 'NoneType' object has no attribute" error due to players not in the json file.  

What is the best way to "skip" the player if it doesn't exist in players.json?

**Comment by ochawkeye** [comment]
This sort of thing just kind of worked itself out last year #86.  It was right around this time of year that NFL.com assigned `gsis_ids` to these missing players.  In the meantime, you could just `try/except` those `AttributeError`s.

```python
import nflgame
import time

ERROR_COUNT = 0

games = nflgame.games(year=2015, week=1, kind='PRE')
players = nflgame.combine_max_stats(games)

for p in players:
	try:
		p.players.position
	except AttributeError:
		ERROR_COUNT += 1

print 'Total Errors: ' , ERROR_COUNT
```
```
Total Errors:  633
```

**Comment by ochawkeye** [comment]
Doh!  It is actually `p.player.position`, not `p.players.position`!

```python
'''
import nflgame
import time

ERROR_COUNT = 0

games = nflgame.games(year=2015, week=1, kind='PRE')
players = nflgame.combine_max_stats(games)

for p in players:
    try:
        p.player.position
    except AttributeError:
        ERROR_COUNT += 1

print 'Total Errors: ' , ERROR_COUNT
```
```
Total Errors:  43
```

**Comment by mesee298** [comment]
Perfect.  Thank you!
