### ISSUE TITLE
Am I going crazy or did somewhere have the list of all players on the field? (likely crazy)

### ISSUE THREAD

**Issue by queuebit** [BurntSushi/nflgame#130]
I was looking into this and nflvid the other day. I had one of the videos fail and I got an error message with one or two urls in the terminal. I opened the url and thought it had a list of all players on the field for a play.

Looking deeper into `nflgame.Game` it seems like it only includes players with a statline for that play. i.e. `(14:55) D.McNabb pass incomplete short right to S.Moss.` only includes players: D.McNabb and S.Moss.

Is this right? Is there another data source that includes all players on the field for a play?

**Comment by BurntSushi** [comment]
I'm not aware of any source of data that provides all players on the field for a given play. That would indeed be quite a find.

**Comment by queuebit** [comment]
Crazy it is. 

Thanks.
