### ISSUE TITLE
Getting rosters from previous years

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#140]
Is there a way to pull rosters from previous years?  It looks like you can get the game jsons all the way back to 2009, so I was hoping I could do the same for rosters.

**Comment by BurntSushi** [comment]
Not really. Roster data is only available in its current form.

With that said, you can recover all of the players that *recorded a statistic* in a particular game. You'll have to iterate over all the `PlayPlayer` events and extract the player info from that.

**Comment by ochawkeye** [comment]
Seemed like a fun one to try to tackle (certainly more fun than watching this Minnesota at San Francisco debacle!)

Maybe this isn't a very good way to go about it, but this does catch those players that have changed teams (you can see that Ndamukong Suh is listed as a DT for Detroit).

I don't really have any idea how often a player might have their positions formally changed, so those will not be reflected and more noticeably it doesn't make any attempt at assigning someone a position if they are no longer on an active roster - those are all dumped under 'UNK'.

https://gist.github.com/ochawkeye/aa0aae0ec42c4ba6ca0e

**Comment by BurntSushi** [comment]
Looks great @ochawkeye!
