### ISSUE TITLE
Some stats are incorrect?

### ISSUE THREAD

**Issue by mattmiddione** [BurntSushi/nflgame#141]
Maybe I'm doing something wrong here, but some of the stats I am seeing do not match what is listed on NFL.com. For example:

games = nflgame.games(2015, home='DET', away='DET')
tmp = nflgame.combine_game_stats(games)
DE1 = tmp.name("J.Jones")

print '%0s' '%7s' '%6s' '%6s' '%5s' '%6s' '%6s' '%5s' % ('Defensive End', 'Tkl', 'Ast', 'Sack', 'FF', 'Int', 'Pdef', 'TDs')
if DE1 != None: print '%0s' '%13s' '%6s' '%6s' '%5s' '%6s' '%6s' '%5s' % (DE1, DE1.defense_tkl, DE1.defense_ast, DE1.defense_sk, DE1.defense_ffum, DE1.defense_int, DE1.defense_pass_def, DE1.defense_frec_tds + DE1.defense_int_tds)

The result is zero stats:

Defensive End    Tkl   Ast  Sack   FF   Int  Pdef  TDs
J.Jones                  0      0     0.0     0     0        0      0

But NFL.com lists him as having 3 tackles, 1 assist, and 1 forced fumble. What am I doing wrong?

**Comment by ochawkeye** [comment]
The were two `J.Jones` playing in yesterday's Detroit game:  `Jacoby Jones (WR, SD)` and `Jason Jones (DE, DET)`.

You'll need to be more specific with your query.  In general, the `gsis_name` is just not a very good way to lookup a player.

```python
import nflgame
games = nflgame.games(2015, home='DET', away='DET')
tmp = nflgame.combine_game_stats(games)

for player in tmp:
	if player.name == 'J.Jones':
		print player, player.playerid, player.player
		print player.formatted_stats()
```
```
J.Jones 00-0025460 Jacoby Jones (WR, SD)
kickret_lng: 24, kickret_lngtd: 0, kickret_ret: 1, kickret_avg: 24, kickret_tds: 0
J.Jones 00-0026194 Jason Jones (DE, DET)
defense_ffum: 1, defense_tkl: 3, defense_int: 0, defense_ast: 1, defense_sk: 0
```

**Comment by BurntSushi** [comment]
Because it's not getting the right player. There are multiple players in that game with the name `J.Jones`. If you do:

```python
print DE1.player
print DE1.formatted_stats()
```

Then you can see what's really going on:

```
Jacoby Jones (WR, SD)
kickret_yds: 24, kickret_ret: 1, puntret_fair: 2
```

I don't know how to give you a fix because you didn't tell us what problem you're trying to solve. If you're trying to "look up player stats by name," then you are trying to solve a **hard problem**. Many players share the same name, so you typically need other mechanisms to narrow down the search, such as team and position. Relatedly, sometimes names are spelled slightly differently than you expect, which means you need some kind of fuzzy match.

[`nfldb`](https://github.com/BurntSushi/nfldb) gives you a lot more tools for player lookup, including fuzzy search and narrowing down players by position/team. There are examples here: https://github.com/BurntSushi/nfldb/wiki/Fuzzy-player-name-matching (This kind of functionality will probably never be in `nflgame`.)

**Comment by BurntSushi** [comment]
@ochawkeye Arrg! You're so quick! :P

**Comment by ochawkeye** [comment]
@BurntSushi Arrg! Your answers are so much more informative!

**Comment by mattmiddione** [comment]
Thanks guys! Sorry for being such a bother. Just getting my feet wet here...

**Comment by mattmiddione** [comment]
Alright, last one of the evening: I want to see who punted the most in week 1 (this year). Why am I getting all zeros here?

import nflgame
games = nflgame.games(2015, week=[1])
players = nflgame.combine(games)
for p in players.punting().sort("punting_tot").limit(10):
    print p, p.punting_tot

R.Allen 0
J.Berry 0
P.O'Donnell 0
T.Masthay 0
J.Hekker 0
J.Ryan 0
B.Anger 0
B.Nortman 0
T.Way 0
M.Darr 0

I'm guessing punt_tot is the wrong stat because it works when I use rushing_yds.

**Comment by ochawkeye** [comment]
That might actually be a change from nfl.com this year as I can't ever say I've seen the stats `punting_pts` before (though to be honest I've never been too interested in punts other than returns).

```python
import nflgame
games = nflgame.games(2015, week=[1])
players = nflgame.combine(games)
for p in players.punting().sort("punting_pts").limit(10):
	print p, p.punting_pts
```
```
S.Lechler 7
D.Colquitt 7
S.Koch 6
M.King 6
B.Anger 5
C.Schmidt 5
S.Martin 5
B.Colquitt 5
K.Huber 5
D.Jones 5
```

I fount that particular stat category by running your exact code block but adding a `p.stats` to what you were printing.

**Comment by mattmiddione** [comment]
OK, what about pass deflections? Bills Safety Aaron Williams is credited with 3 deflections on NFL.com during week 1 of the 2015 NFL season, but nflgame says he had zero. Any ideas?

import nflgame
games = nflgame.games(2015, week=[1])
players = nflgame.combine(games)
for p in players.defense().sort("defense_pass_def").limit(10):
    print p, p.defense_pass_def

C.Jones 0
T.Brown 0
J.Mayo 0
J.Collins 0
D.Harmon 0
B.Fletcher 0
A.Branch 0
P.Chung 0
R.Ninkovich 0
D.McCourty 0

Printing p.stats doesn't seem to include anything related to deflections:

C.Jones 0
OrderedDict([(u'defense_ffum', 0), (u'defense_tkl', 1), (u'defense_int', 0), (u'defense_ast', 2), (u'defense_sk', 0)])

Thanks guys!

**Comment by BurntSushi** [comment]
Try using `combine_max_stats` or `combine_play_stats` instead of just `combine` (which is deprecated). Check out the API docs: http://pdoc.burntsushi.net/nflgame#nflgame.combine

**Comment by ochawkeye** [comment]
Maybe worth noting:  One area hung me up in trying to do this (and it makes sense now that I've seen it thought wasn't immediately intuitive to me) is that these two similar blocks of code produce different results.

```python
import nflgame
games = nflgame.games(2015, 1)

players = nflgame.combine_max_stats(games).filter(defense_pass_def__ge=1)
for player in players.sort("defense_pass_def").limit(10):
	print player, player.defense_pass_def

players = nflgame.combine_max_stats(games).filter(defense_pass_def=True)
for player in players.sort("defense_pass_def").limit(10):
	print player, player.defense_pass_def
```
On a play-by-play basis for stats like `defense_pass_def` or `kickret_ret` maybe they are equivalent , but on aggregated they definitely are not.

**Comment by BurntSushi** [comment]
@ochawkeye Who says Python has "strong" typing? :P `True + 1 == 2` and `True == 1` are both totally valid!

**Comment by mattmiddione** [comment]
Thank guys!
