### ISSUE TITLE
player statistics per play?

### ISSUE THREAD

**Issue by McQdev** [BurntSushi/nflgame#143]
Howdy:

I'm struggling to get a list of player statistics iterated across a given game (or all games). Not just the play description, but the raw statistics as well. i.e. I'd like to feed in a game (or several) and get something akin to [game time, Player name, statname, value, stat name, value, stat name, value (etc.)] for every play. 

Ultimately I'm trying to build a timestamped csv of all plays which contain fantasy-storable statistics that can be then used for visualization. I'm a bit amateur at python, but I spent the last few days building a system that (mostly) successfully does this by parsing searching the html version of the play-by-play... it throws any number of false positives and negatives, though it catches the vast majority of legitimate plays. I figured going from the raw .json would be far more accurate, and this api looks like the best way to do that. 

I just can't quite figure out how to get what I want. Any help?

**Comment by ochawkeye** [comment]
Since each play will have multiple players
```python
import nflgame

games = nflgame.games(year=2015, week=1)
plays = nflgame.combine_plays(games)
for play in plays:
	for player in play.players:
		print play.time, player.player.name, player.formatted_stats()
```
```
Q1 15:00 Stephen Gostkowski kicking_all_yds: 74, kicking_yds: 65, kicking_tot: 1, kicking_touchback: 1
Q1 15:00 Dont'a Hightower defense_tkl: 1
Q1 15:00 DeAngelo Williams rushing_att: 1, rushing_yds: 18
.
<6039 lines later>
.
Q4 02:00 Carlos Hyde rushing_att: 1, rushing_yds: 5
Q4 01:15 Colin Kaepernick rushing_att: 1, rushing_yds: -1
Q4 00:35 Colin Kaepernick rushing_att: 1, rushing_yds: -1
```

**Comment by McQdev** [comment]
You're a hero, this thing is incredible, and I'm an idiot. 

Thanks forever.

**Comment by ochawkeye** [comment]
How successful were you in parsing the html play by play?

**Comment by McQdev** [comment]
I managed to get correct values for the 3 QBs I manually entered. Haven't tested on all games yet, and haven't added language to search for other offensive players, kickers, and team def. 

80% of the code is cleaning up the html, running through beautifulsoup and reformatting into a list of lists for easy CSV export. Because I'm not great at this, it's all poorly cobbled together, but it works. 

Happy to toss it up here and share, if you'd like, and I'd love any feedback on how god-awful it is, or what looks pretty good.

**Comment by BurntSushi** [comment]
@McQdev Are you parsing the play-by-play text descriptions? Or extracting stats from a table somewhere? The former is exceedingly difficult. If we had a solid method to do it, then we could get stats going back to 1999 I think.

**Comment by McQdev** [comment]
Parsing the text desc. You're right... it is exceedingly difficult, and I'm sure my method is pretty poor. I've been tweaking it to track down false positives and negatives, but those text descriptions are all over the place. 

As an example, I'm getting passing yards with:

```
if QB in gamelog[i][5] and  "pass" in gamelog[i][5] and "incomplete" not in gamelog[i][5] and "No Play" not in gamelog[i][5] and "INTERCEPTED" not in gamelog[i][5]:
    m = re.search('for (.+?) yard', gamelog[i][5])
       if m:
            gamelog[i][6]+=float(m.group(1))*1/25
```

which is ridiculous and you can see how long that conditional could stretch. 

I think to clean it up, you'd have to make a first pass with rough methods and maybe a second pass with some kind of NL technique, but that's way beyond my skill set.

**Comment by BurntSushi** [comment]
Ya, I do think it's a tractable problem, but a hard and tedious one. NL or even ML might be necessary.
