### ISSUE TITLE
Separate team rosters by game

### ISSUE THREAD

**Issue by gigivacca** [BurntSushi/nflgame#145]
Hello,
Congrats on the code. Let's say I want to know which players played in a given name for a given team.
I follow your example:
game = nflgame.one(2011, 17, "NE","BUF")
z= game.players
count=0
for iz,zitem in enumerate(z):
    print zitem
    print iz

Following this example, where the NE player list ends and where  the Buffalo players start?
I can guess this but I am looking for a programmatical solution. 

Thanks,

Gigi

**Comment by ochawkeye** [comment]
Each of your "zitem"'s has a ".team" property.

**Comment by ochawkeye** [comment]
```python
import nflgame
game = nflgame.one(2011, 17, "NE","BUF")
z= game.players
count=0
for iz,zitem in enumerate(z):
	print iz, zitem, zitem.team, zitem.home
```
```
0 B.Hoyer NE True
1 T.Brady NE True
...
27 S.Moore NE True
28 R.Fitzpatrick BUF False
...
59 A.Williams BUF False
60 D.Edwards BUF False
```
