### ISSUE TITLE
Play by Play Data (complete) in CSV format

### ISSUE THREAD

**Issue by RSABryan** [BurntSushi/nflgame#149]
Hi guys, I've fooled around with a bunch of variations of the sample code in order to pull base play by play data...

First off, here's what I'm looking for. This is from a sample play by play dataset I downloaded for 2014:

![2015-09-22 04_09_45-cortana](https://cloud.githubusercontent.com/assets/14686110/10062258/c6cce82a-622e-11e5-9374-279d54c34ba1.jpg)

When I try:

game1 = nflgame.games(2015, week=1)
game1.csv("w1.csv")

I get, "AttributeError: 'list' object has no attribute 'csv'", ok so that makes sense.

Then I try the more direct route:
nflgame.games(2015, week=1).csv("w1.csv")

Same error, different tune...

When I try with the combine statement I get a nice file that has stats for each player, again I'm looking for the more granular play by play data.

I have also tried:

import nflgame
import csv
games = nflgame.games(2015, week=1)
plays = nflgame.combine_plays(games)

with open('w1.csv', 'wb') as f:
     w = csv.writer(f)
     w.writerow(['playid', 'down', 'home', 'team', 'touchdown', 'yards_togo', 'total_yds', 'turnovers', 'rushing_yds', 'passing_yds'])
     for play in plays:
          data = []
          try:
               data.append(plays.play.playid)
               data.append(plays.play.down)
               data.append(plays.play.home)
               data.append(plays.play.team)
               data.append(plays.play.touchdown)
               data.append(plays.play.yards_togo)
               data.append(plays.TeamStats.total_yds)
               data.append(plays.TeamStats.turnovers)
               data.append(plays.TeamStats.rushing_yds)
               data.append(plays.TeamStats.passing_yds)
          except AttributeError:
               data.append('no meta data available')
          w.writerow(data)

But all I get is a bunch of rows with "no meta data available".  (I'm assuming that some of the rows above are not formulated correctly and/or I have incorrect attribute syntax)

Any thoughts here guys and gals?

Thanks
RSABryan

**Comment by andr3w321** [comment]
This ought to get you started.  Take a look at http://pdoc.burntsushi.net/nfldb#nfldb.Play and https://github.com/BurntSushi/nflgame/issues/144

To get the attributes...
```
dir(play) yeilds
['_Play__players', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_stats', 'data', 'desc', 'down', 'drive', 'events', 'has_player', 'home', 'note', 'passing_att', 'passing_incmp', 'passing_incmp_air_yds', 'players', 'playid', 'receiving_tar', 'team', 'third_down_att', 'third_down_failed', 'time', 'touchdown', 'yardline', 'yards_togo']
```

```
import nflgame

games = nflgame.games(year=2015, week=1)
plays = nflgame.combine_plays(games)
for play in plays:
    print play.down, play.yards_togo
```

```
4 1
0 0
1 10
2 1
1 10
1 10
2 16
3 15
4 8
1 10
2 7
0 0
1 10
2 5
3 6
0 0
```

I'm not sure why, but I couldn't access plays[0] as apparently it's not indexable

**Comment by RSABryan** [comment]
Thanks, that is extremely helpful.

Followup question though, there is a key piece of information missing here, in yards gained.  It's odd that things like "passing incmp" and "third_down_att" are included but something as simple as the resulting yards is missing.

Did I miss that field in the spec (it's early but I have had my coffee) or is there another cross ref we have to do on the playid to get that?

Thanks again for your help.  The previous reply was right on.

RSABryan

**Comment by ochawkeye** [comment]
I think what you are seeing on @andr3w321 printout of `dir(play)` are the attributes that were available on the very last play of a game which is the play `END GAME`.  The end of the game doesn't have any yards gained.

Checking out the second to last play of week 1 exposes a few more attributes:
```
(SF, MIN 32, Q4, 3 and 6) (:35) C.Kaepernick kneels to MIN 33 for -1 yards.
['_Play__players', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattr__', '__getattribute_
_', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__',
'__str__', '__subclasshook__', '__weakref__', '_stats', 'data', 'desc', 'down', 'drive', 'events', 'has_player', 'home', 'not
e', 'players', 'playid', 'rushing_att', 'rushing_yds', 'team', 'third_down_att', 'third_down_failed', 'time', 'touchdown', 'y
ardline', 'yards_togo']
```

A pass play:
```
(MIN, SF 45, Q4, 3 and 15) (3:42) (Shotgun) T.Bridgewater pass short left to M.Asiata to SF 38 for 7 yards (N.Bowman). Caught
 at SF 41.  3-yds YAC
['_Play__players', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattr__', '__getattribute_
_', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__',
'__str__', '__subclasshook__', '__weakref__', '_stats', 'data', 'defense_tkl', 'desc', 'down', 'drive', 'events', 'has_player
', 'home', 'note', 'passing_att', 'passing_cmp', 'passing_cmp_air_yds', 'passing_yds', 'players', 'playid', 'receiving_rec',
'receiving_tar', 'receiving_yac_yds', 'receiving_yds', 'team', 'third_down_att', 'third_down_failed', 'time', 'touchdown', 'y
ardline', 'yards_togo']
```

With those examples you start to see some of what you're looking for with `rushing_yds` and `passing_yds` and `receiving_yds` (oh my)

**Comment by ochawkeye** [comment]
> But all I get is a bunch of rows with "no meta data available".

Your `try` portion of your `try/except` block is pretty big.  If *any* part of it fails, you're going to bail out to the except.  In your case, *none* of that append lines work.  I think you might have jumped into catching exceptions (and thus hiding your problems) before you succeeded in ever getting what you were looking for. ;)

1. `data.append(plays.play.playid)` - you do `for play in plays` but then try to access `plays`; can't do it
2. Appending `play.X` works out if you KNOW that attribute is present, but as seen earlier, attributes of a play can change depending on what type of play it was.  You should use the `getattr` wrapper instead of trying to grab and attribute that may or may not be there.
3. `TeamStats` are "A collection of team statistics for an entire game". They don't exist on a per play basis

Some of the things you are looking for aren't natively included in the play-by-play data but are easy enough to assemble ourselves.

Have a look at this for some ideas:
```python
import nflgame
import csv
games = nflgame.games(2015, week=1, home='MIN', away='MIN')
plays = nflgame.combine_plays(games)

with open('w1.csv', 'wb') as f:
    w = csv.writer(f)
    w.writerow(['playid', 'down', 'home', 'team', 'touchdown', 'yards_togo', 'total_yds', 'turnovers', 'rushing_yds', 'passing_yds'])

    def turnovers(p):
        return p.passing_int or p.fumbles_lost
    def total_yards(p):
        return (getattr(p, 'rushing_yds')) + (getattr(p, 'passing_yds'))

    for play in plays:
        data = []
        failures = 'no meta data available'
        data.append(getattr(play, 'playid'))
        data.append(getattr(play, 'down'))
        data.append(getattr(play, 'home'))
        data.append(getattr(play, 'team'))
        data.append(getattr(play, 'touchdown'))
        data.append(getattr(play, 'yards_togo'))
        # data.append(getattr(play, 'total_yds'))  # This one doesn't exist
        data.append(total_yards(play))
        # data.append(getattr(play, 'turnovers'))  # This one doesn't exist
        data.append(turnovers(play))
        data.append(getattr(play, 'rushing_yds'))
        data.append(getattr(play, 'passing_yds'))
        w.writerow(data)
```

**Comment by ochawkeye** [comment]
EDIT to point 2 above...guess it's not actually necessary to use `getattr`.

```python
    data.append(play.rushing_yds)
    data.append(play.passing_yds)
```
work just find, defaulting in a `0` if that stat is not present on the play

**Comment by RSABryan** [comment]
Guys, this is fantastic!  I think I just needed a nudge in the right direction (syntax is new to me as well).  With a few modifications from the above I have the exact data set I was looking for.

Thanks to you both.  I'm glad this is published here, hopefully will help other folks as well.

RSABryan
