### ISSUE TITLE
Creating Player

### ISSUE THREAD

**Issue by zachpanz88** [BurntSushi/nflgame#153]
How do I create an obejct of this class? The directions are confusing. Also, what type does the home parameter accept?

def __init__(self, playerid, name, home, team)

"Create a new Player instance with the player id (from NFL.com's GameCenter), the player's name (e.g., "T.Brady") and whether the player is playing in a home game or not."

**Comment by zachpanz88** [comment]
Issue solved

**Comment by BurntSushi** [comment]
That's not the `Player` class. That's the `PlayerStats` class.

Python doesn't have good tools for indicating public/private. You really shouldn't be creating `PlayerStats` objects manually.

**Comment by BurntSushi** [comment]
@zachpanz88 If you solved your issue, it would be helpful to report how you solved it so that others can learn.

**Comment by zachpanz88** [comment]
I created the player object by searching for the player using the "def find(name, team=None)" rather than attempting to manually create the object.
