### ISSUE TITLE
Week 4 London Game Time Was Off

### ISSUE THREAD

**Issue by Ryanharstco** [BurntSushi/nflgame#156]
The Jets-Fins game in London started at 9AM EDT, but came through in the API as starting at 9PM.

**Comment by andr3w321** [comment]
See https://github.com/BurntSushi/nfldb/issues/107

**Comment by BurntSushi** [comment]
@Ryanharstco Where exactly are you seeing "9PM"? nflgame passes the time reported from NFL.com unaltered. Therefore, it's a bit harder to fix than in nfldb.

**Comment by Ryanharstco** [comment]
Hey Andrew!

We are seeing it in our instance of nfldb.



---Sent on my Apple piPhone---

**Comment by BurntSushi** [comment]
@Ryanharstco Please see the linked issue.........

**Comment by BurntSushi** [comment]
@Ryanharstco If you're having issues with nfldb, then please file issues on the nfldb repository. This is the nflgame repository.

**Comment by Ryanharstco** [comment]
My bad



---Sent on my Apple piPhone---
