### ISSUE TITLE
gsis_name error

### ISSUE THREAD

**Issue by zachpanz88** [BurntSushi/nflgame#157]
There is no gsis_name property for Odell Beckham Jr.
```
player = nflgame.find("Odell Beckham", team=None)
playername = player[0].gsis_name
print playername
```
The above code does not print anything. 

```
player = nflgame.find("Julio Jones", team=None)
playername = player[0].gsis_name
print playername
```
The above code prints "J.Jones"

It should print O.Beckham Jr. because that is one of the names that is supplied from:
```
game = nflgame.games(2015, week=4)
players = nflgame.combine_game_stats(game)
for p in players.receiving():
    print p.name
```
Note: "player = nflgame.find("Odell Beckham", team=None)" does find a player object, but "player = nflgame.find("Odell Beckham Jr.", team=None)" or "player = nflgame.find("Odell Beckham Jr", team=None)" does not find anything.

The player object for Odell Beckham Jr. still has other properties such as his team and number.

**Comment by BurntSushi** [comment]
I'm not sure about why his name isn't showing up, but you shouldn't expect `find` to work for any particular name. It does exact matching. If you don't pass the name exactly right, it may not find anything.

**Comment by zachpanz88** [comment]
What I am saying is that when I use 
```
player = nflgame.find("Odell Beckham", team=None)
```
It gives me a player object. This object has correct attributes such as position (WR) and number (13) but does not have a gsis_name attribute.

**Comment by BurntSushi** [comment]
Fixed. Please upgrade nflgame.

**Comment by zachpanz88** [comment]
It works now, thanks.
