### ISSUE TITLE
Bye Weeks

### ISSUE THREAD

**Issue by zachpanz88** [BurntSushi/nflgame#158]
Is there any way to find the bye week of a team in a certain season, such as passing a team name and year as an argument, or just a way to find a bye week for a team in the current season? Thanks.

**Comment by BurntSushi** [comment]
There isn't anything convenient in the API, no. You'll have to iterate over the games in a season yourself and find out which week a team didn't play.

**Comment by andr3w321** [comment]
select week from game where (home_team = 'CAR' or away_team = 'CAR') and season_year = 2014 and season_type = 'Regular' order by week;
 week 
------
    1
    2
    3
    4
    5
    6
    7
    8
    9
   10
   11
   13
   14
   15
   16
   17
(16 rows)

Then check to see which # is not in `weeks = range(1,18)`

**Comment by zachpanz88** [comment]
For future reference this code finds the bye week of any team. Unfortunately, it cannot find the bye week unless that bye week has already occurred (unless someone would like to improve my code), meaning that some 2015 teams will not return a bye week (yet).

```
import nflgame

def byeweek(team, year):
    games = nflgame.games(year, week=None, home=team, away=team, kind='REG', started=False)
    bye = 0
    gamedetails = []
    weeks = []
    for x in range(0,len(games)):
        gamedetails.append(games[x].schedule)
    for x in range(0,len(gamedetails)):
        weeks.append(gamedetails[x]['week'])
    for x in range(1,len(weeks)):
        if x not in weeks:
            bye = x
            break
    return bye
```

Note: I know this is probably not the most efficient code, but it works for me
