### ISSUE TITLE
no gsis_name property

### ISSUE THREAD

**Issue by zachpanz88** [BurntSushi/nflgame#159]
Again, the issue I presented before is occurring with the player object for Tyler Lockett. The object has no gsis_name property, but has the other property such as name, number, etc.

**Comment by BurntSushi** [comment]
@zachpanz88 Delete the entry from `players.json` and re-run `nflgame-update-players`. (This is what I did to fix the issue last time.)

**Comment by zachpanz88** [comment]
Since there are a bunch of players with this issue, it is just easier to run this to get the gsis name:

```python
player = nflgame.find("Tyler Lockett", team=None)[0]
playername = player.first_name[0]+"."+player.last_name
```

**Comment by BurntSushi** [comment]
No, that isn't the gsis_name. The gsis_name is usually of the form "{First Initial}.{Last Name}" but has some variation.

**Comment by BurntSushi** [comment]
If there are a bunch of players with that issue, then the right thing is to delete their records from players.json and re-run nflgame-update-players.

**Comment by ochawkeye** [comment]
See: Ka.Williams (BUF), De.Williams (PIT),  JO.Brown (ARI), JA.Brown (ARI)
for examples from last week.

For a time in 2013 I recall Julio Jones' gsis_name was JulioJones ignoring
common syntax entirely.

**Comment by zachpanz88** [comment]
I wrote a script to find every player without a gsis_name and write that to a new file. I then replaced players.json with that file. I ran nflgame-update-players and it added 446 players. When I viewed the players.json, the players that were removed by my script and missing a gsis_name were replaced, but they still contained the same properties they did originally (no gsis_name). The changes to the file were about 5,000 lines deleted and 400 lines added (according to git). I am not sure what I did wrong or if getting the gsis_name is a bug.

**Comment by zachpanz88** [comment]
Essentially, I am looking to compare players and my code looks like this:

```python
playerlist = nflgame.find(name, team=None)
    if playerlist == []:
        return False
    else:
        player = playerlist[0]
        games = nflgame.games(year, week=wk)
        gameplayers = nflgame.combine_game_stats(games)
        for p in gameplayers:
            if p.name == player.gsis_name:
                # copy stats
```
Is there any other way to compare the players such as using the player's id?

**Comment by BurntSushi** [comment]
If you just want to compare players, then yes, use their id...

I'm not sure what you did wrong. Some players may not have a gsis name. A player only has a gsis name if they recorded a statistical event in a game. Otherwise, they never show in the game data and are therefore never assigned a gsis name.

Some players that *do* have a gsis name might not have gotten one because they were added to the players list before they recorded a statistical event. I guess they never got updated (because updating every player is very expensive).

**Comment by zachpanz88** [comment]
How would I compare compare players using this, because there is no id or gsis_id property of p
``python
games = nflgame.games(year, week=wk)
    gameplayers = nflgame.combine_game_stats(games)
    for p in gameplayers:
        # if p.name == player.gsis_name:
```

**Comment by BurntSushi** [comment]
Use `print dir(p)` to see available attributes. e.g., `p.playerid`.

**Comment by zachpanz88** [comment]
Ok, that works better and solves my issue, pretty dumb that I didn't think of that first...
