### ISSUE TITLE
Fumble recoveries for TDs don't show up in player stats

### ISSUE THREAD

**Issue by mrdhammer** [BurntSushi/nflgame#161]
I can't seem to find a way to look up fumble recoveries for TDs by offensive players using the PlayerStats. Any idea what's going on here?  

player = nflgame.find("Julio Jones")
player_stats = player[0].stats(2015, 5)
player_stats.fumbles_rec_tds
>>>> 0

But if I use combine_max_plays:
games = nflgame.games(year=2015, week=5, home='ATL', away='ATL')
plays = nflgame.combine_max_stats(games)
for p in plays:
  if p.name == "J.Jones":
    print p.name, p.fumbles_rec_tds
>>>> J.Jones 1

**Comment by BurntSushi** [comment]
It's because `player[0].stats` retrieves game level statistics (look at its source). To get play level stats, you'll need to fetch the play sequence and extract the player. This will aggregate statistics for you. e.g.,

```
>>> julio = nflgame.find('Julio Jones')[0]
>>> stats = julio.plays(2015, week=5).players().playerid(julio.playerid)
>>> stats.formatted_stats()
'receiving_tar: 10, fumbles_tot: 1, fumbles_forced: 1, fumbles_rec: 2, fumbles_rec_yds: 0, receiving_yds: 67, receivin
g_rec: 5, receiving_yac_yds: 30, fumbles_rec_tds: 1'
```
