### ISSUE TITLE
list of dicts for json 'key' values

### ISSUE THREAD

**Issue by hackerDEpandas** [BurntSushi/nflgame#162]
I was wondering if there was a place where I could find all the 'key' values of the json. For example in the first example on the [documentation](http://pdoc.burntsushi.net/nflgame) page, after a few lines of code, you see this...
```
players = nflgame.combine_game_stats(games)
for p in players.rushing().sort('rushing_yds').limit(5):
```

In the rushing method what other 'key' values can we use other than ```'rushing_yds'```. I would like to see all the options I have for filtering player stats and would greatly appreciate any information to help me find all the 'keys' in all the methods.

**Comment by BurntSushi** [comment]
They are unintuitively documented as [part of the `nfldb` project](https://github.com/BurntSushi/nfldb/wiki/Statistical-categories).

**Comment by ochawkeye** [comment]
As the unofficial defender of `nflgame` I'm obligated to point out that many (...most...all?) of these are included in the nflgame [wiki](https://github.com/BurntSushi/nflgame/wiki/Stat-types).

**Comment by BurntSushi** [comment]
@ochawkeye Haha. Totally forgot about that!
