### ISSUE TITLE
Downloading a Schedule of all NFL Games

### ISSUE THREAD

**Issue by johnjsyoo** [BurntSushi/nflgame#164]
I was having a problem earlier with downloading the 2015 schedule of games using the nflgame.schedulegames module.  To me it seems as though this is deprecated and nflgame.sched is the new convention.  If this is the case, the markdown here could be updated:

from schedule_games = nflgame.schedule.games to schedule_games = nflgame.sched.games

https://github.com/BurntSushi/nflgame/wiki/Cookbook#create-a-csv-file-with-all-games-in-the-2013-regular-season

Also, when looking at the example code, I noted that the 'schedule_games" variable was an ordered dictionary.  The JSON or python code may have changed the and I was getting a 'too many values to unpack error' (Python 2.7).  I tried using iteritems() to work around this, but ended up just calling out each dictionary value by key.  This portion may need a look at as well.

schedule_games = nflgame.schedule.games

**Comment by rimig** [comment]
Had the same issue. This works:

```
import nflgame
import nflgame.sched
import csv

schedule_games = nflgame.sched.games

with open('2015 Schedule.csv', 'wb') as csvfile:
    schedulewriter = csv.writer(csvfile, delimiter=',')
    schedulewriter.writerow(['Home', 'Away', 'Week', 'Year'])
    for key in schedule_games:
        game = schedule_games[key]
        if game['year'] == 2015 and game['season_type'] == 'REG':
            schedulewriter.writerow([game['home'], game['away'], game['week'], game['year']])
```

**Comment by rimig** [comment]
I just updated the wiki btw

**Comment by johnjsyoo** [comment]
Yeap! That's pretty much exactly what I had to do as well.
