### ISSUE TITLE
Json's for injuries and inactives?

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#170]
Andrew, have you looked to see if you can get jsons from NFL.com/injuries and NFL.com/inactives?  I would love to start grabbing that information other than just trying to scrape NFL's pages. Not sure if there are jsons, but thought you might know.

**Comment by BurntSushi** [comment]
I haven't looked.

**Comment by mesee298** [comment]
How would I look to see if there are jsons?

**Comment by BurntSushi** [comment]
Use Chrome or Firefox's development tools to inspect what data is being transferred in the web page.

I don't really know what your experience level is, so I don't know how to give you more targeted advice. For example, if you've never done web development/programming before, then I expect it might be rather difficult to check.

**Comment by mesee298** [comment]
Got it. Thank you.

**Comment by cranst0n** [comment]
FYI, it looks like they query injury data on the backend and send it over embedded within the `nfl.com/injuries` HTML document:

```html
  ...
  <script type="text/javascript">
    ...
    var dataAway = [        
        {player: "McCown Joshua ",   position: "QB", injury: "right Shoulder", practiceStatus: "Did Not Participate In Practice", gameStatus: "Out", lastName: "McCown", firstName: "Joshua", esbId: "MCC600777"  },
        {player: "Poyer Jordan ",   position: "S", injury: "Shoulder", practiceStatus: "Did Not Participate In Practice", gameStatus: "Out", lastName: "Poyer", firstName: "Jordan", esbId: "POY177981"  },
    ...
```
