### ISSUE TITLE
Future Opponent

### ISSUE THREAD

**Issue by zachpanz88** [BurntSushi/nflgame#171]
I am wondering if there is a way to find what opponent a team will be facing in the future. I am trying to provide predictions, so I need to have a way to find what team a player is facing in the next week. Currently, `nflgame.one()` only finds games that have already occurred.

**Comment by BurntSushi** [comment]
You'll have to access the raw schedule data: https://github.com/BurntSushi/nflgame/blob/master/nflgame/sched.py#L49

Alternatively, use `nfldb`, which will return games that haven't been played yet in its primary query API.

**Comment by zachpanz88** [comment]
Works perfectly, thanks
