### ISSUE TITLE
Player Stats

### ISSUE THREAD

**Issue by Kaw5600** [BurntSushi/nflgame#172]
After reviewing the documentation, i see how to retrieve information on a particular player for a particular game but is there an example of how to get all player stats from a particular season? should i be using nfldb?

**Comment by ochawkeye** [comment]
How are you retrieving player stats for a single game?

Here is one way to get for a single week:
```python
import nflgame
games = nflgame.games(year=2015, week=8)
players = nflgame.combine_game_stats(games)
for player in players:
    print player, player.formatted_stats()
```

To do that for an entire season, just omit the week.
```python
import nflgame
games = nflgame.games(year=2015)
players = nflgame.combine_game_stats(games)
for player in players:
    print player, player.formatted_stats()
```

Worth noting, week can also be a list of weeks:
```python
import nflgame
games = nflgame.games(year=2015, week=[7, 8])
players = nflgame.combine_game_stats(games)
for player in players:
    print player, player.formatted_stats()
```

> should i be using nfldb?
You don't have to, but you can:
```python
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2015, season_type='Regular')

for pp in q.as_aggregate():
    print pp.player, pp
```

**Comment by Kaw5600** [comment]
my "fear" with using nfldb is that i want to push the information that i get from the api to my db in mysql to perform certain calculations. importing nfldb has been a bit of a problem for me

**Comment by BurntSushi** [comment]
@Kaw5600 Can you describe the problems you're having with `nfldb`?

**Comment by Kaw5600** [comment]
i get an error that says "Command python setup.py egg_info failed with error code 1
"
im assuming its because i did not download/install the DB the instructions gave

**Comment by BurntSushi** [comment]
@Kaw5600 Unfortunately, that isn't enough information to allow us to help you. We need to know what command you ran and the *full* output of that command.

**Comment by Kaw5600** [comment]
sorry about that, here it is:
![1](https://cloud.githubusercontent.com/assets/14000966/10911187/abe7a826-8211-11e5-947b-f9c7111da430.PNG)

**Comment by BurntSushi** [comment]
@Kaw5600 You need to install postgres: http://stackoverflow.com/questions/11618898/pg-config-executable-not-found

**Comment by Kaw5600** [comment]
Thanks!

**Comment by Kaw5600** [comment]
(beware, a "noob" question) i have a windows machine and running linux (ubuntu) on a virtual server. Which should i download?

**Comment by BurntSushi** [comment]
I don't understand the question. I always recommend `nfldb` over `nflgame` if you can manage it because the API is much easier to use and it is much faster. I would recommend reading the wiki for full details.

**Comment by Kaw5600** [comment]
i wasnt sure if i should download the windows or linux version of Postgres since i am on a windows machine but using linux (ubuntu) in a virtual env in putty.

**Comment by BurntSushi** [comment]
You need to download whatever version you're installing it on. If you're installing it on Linux, you really shouldn't be downloading anything at all. Instead, use your distro's package manager (e.g., `apt-get` for Ubuntu).

**Comment by Kaw5600** [comment]
can i retrieve team stats from a season using nflgame instead of nfldb? If so, is there a very basic example?
