### ISSUE TITLE
Team Roster

### ISSUE THREAD

**Issue by Kaw5600** [BurntSushi/nflgame#177]
i have been using this to retrieve the current team rosters for a team: (with the help of @BurntSushi )
![teamrosterhelp](https://cloud.githubusercontent.com/assets/14000966/11383591/3e8dab8c-92d7-11e5-97b7-a68f148f2b60.PNG)

Is there a way to get the roster for all teams instead of just a single specified team?

**Comment by ochawkeye** [comment]
```python
import nflgame
for p in nflgame.players.itervalues():
    print p.full_name, p.position, p.team
```
