### ISSUE TITLE
Flex games

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#183]
There is a change to the NFL schedule (i.e. Flex game), but when I run the NFL Schedule program, it is not updating.  Is there something else I have to do to make the changes happen?

Also, is there a way to get AM or PM added or show in military time?

**Comment by BurntSushi** [comment]
What did you try? `nflgame-update-schedule --year 2015` should work. The schedule has a `meridiem` field that should have PM/AM info.

**Comment by mesee298** [comment]
Thanks for the quick response.  So, I got the first problem taken care of, but I don't see a meridiem field.  Below is a snippet of the schedule.json file.  Is there another way I should be pulling it?

  [
   "2015121303",
   {
    "away": "NE",
    "day": 13,
    "eid": "2015121303",
    "gamekey": "56700",
    "home": "HOU",
    "month": 12,
    "season_type": "REG",
    "time": "8:30",
    "wday": "Sun",
    "week": 14,
    "year": 2015
   }
  ],

**Comment by BurntSushi** [comment]
`meridiem` is a new feature. You'll need to update `nflgame`. It might not be on all of the games yet, but it should appear after running the command in my previous comment. You can see it here: https://raw.githubusercontent.com/BurntSushi/nflgame/master/nflgame/schedule.json

Note that [`nfldb`](https://github.com/BurntSushi/nfldb) keeps all times in UTC, which might make this easier.

**Comment by mesee298** [comment]
Awesome. Thanks.  I plan on looking at nfldb next year (you have beat me up enough about it :) ).
