### ISSUE TITLE
Issues with JSON data

### ISSUE THREAD

**Issue by tulimaki** [BurntSushi/nflgame#186]
Hi,

been exploring this project lately.

1. There is some issues with JSON data here and there. Most of them is in preseason games and I ignored those.
2. 2013 week 14 MIA@PIT (2013120806) seems to be missing punch of plays in 4th quarter. Like one Miami touchdown and field goal.
3. 2015 week 13 CAR@NO (2015120607) introduced couple of new stats 403 -> Defensive two point attempt? and 404 -> Defensive two point attempt successful?

I understand these are NFL game-center JSON files and there is not much to do.

How have you dealt with these issues? Current data on MIA@PIT game gives wrong winner since it is missing plays.

Also NFL.com offers schedules for games 2001-2008, but the game JSON-files is not available. Do you know if these game files is available somewhere?  I see your statsmap file refers to these seasons also.

**Comment by BurntSushi** [comment]
There is a lot of information related to your questions in the issue tracker. I'd recommend running a few searches.

With that said, your first line of defense is to delete the offending the JSON and call `nflgame.one` for the corresponding game. It will re-download the JSON. On occasion, it will be fixed. When it is not fixed, there is not much we can do and it is outside the scope of nflgame. nflgame is meant to provide a convenient API to the JSON data. If the underlying data is flawed, then so is nflgame.

> Do you know if these game files is available somewhere?

If they were available then nflgame would use them.
