### ISSUE TITLE
How to retrieve games played in a season for a player

### ISSUE THREAD

**Issue by travisscone** [BurntSushi/nflgame#207]
I am looking for a way to query the database and return the # of games a player played in for any given season. Anyone found a way to do this? Thanks in advance!

**Comment by ochawkeye** [comment]
A previous discussion on the topic: https://github.com/BurntSushi/nflgame/issues/69

Keep in mind the `player.games` is not guaranteed to be the number of games a player played in - only the number of games a player recorded a statistic in.
