### ISSUE TITLE
College Version?

### ISSUE THREAD

**Issue by pdbethke** [BurntSushi/nflgame#210]
This may have been covered before, but is there any possiblity of a college (NCAA Div I for example) version? I'm assuming the root issue is finding a feed that approximates the one used for the NFL version and adapting that? I'm working on a fantasy football app that covers the collegiate schedule and this would be immensely helpful in automatically scoring the results.

**Comment by BurntSushi** [comment]
No, sorry, precisely for the reasons you stated.

**Comment by pdbethke** [comment]
Understood - Although I did discover the feeds provided by Sportradar, eg.  http://developer.sportradar.us/docs/NCAA_Football_API. They offer a 3-month developer trial and the data is very useful, though after the trail you need to pay for it, obviously.
