### ISSUE TITLE
Help Getting this working

### ISSUE THREAD

**Issue by donlaur** [BurntSushi/nflgame#214]
Hello, Not sure where to post this.  I have emailed before to the list and I have tried to figure this out by Python and Postgresql isn't my in my skills at the moment.  I have reached out to get postgresql on my server and in cpanel but it just seems to spin without doing anything and time is running out to get this working.

I have followed along but still pretty lost on getting the data setup to schedule and import into the db.

Would anyone be willing to take some money to get this and nfldb up and working into the database?  I am more familiar with PHP and mySQL, but if I can get the info into the postgresql I can find a PHP way to query it out.  I want to have a page that lists plays and total stats, not live but near live as I can get, and include daily fantasy scoring.  That part, I can do, with formulas but I need to get the system up and running first.  

Thanks.

**Comment by BurntSushi** [comment]
Sorry you're having so much trouble, but I'd really encourage you to read the documentation. There is a complete walkthrough on how to install `nfldb`: https://github.com/BurntSushi/nfldb/wiki --- What would be useful is for you to try that and create a new issue with any specific problems you're running into, including providing more information about your environment and which step in the tutorial you're on. I don't know anything about cPanel, so I can't help you there.

I'm going to close this issue for a couple reasons:

1. This is the `nflgame` repository but you're asking for help on setting up `nfldb`. Please file `nfldb` related issues on the `nfldb` repository: https://github.com/BurntSushi/nfldb
2. I'm not sure this is really the right place to be soliciting money in exchange for services. There are lots of other web sites built for that purpose. I suggest you use one of those.

**Comment by donlaur** [comment]
I just need someone to help me get it working.  I emailed directly and I was told to ask here, I have read the documents and the wiki.  Just looking for someone to help for nflgame and nfldb.

**Comment by ochawkeye** [comment]
@donlaur What's not working?  An error code or screen shot would be helpful.  What operating system is your server using?  Did you catch [install](https://github.com/BurntSushi/nfldb/wiki/Installation) and/or ;Windows install](https://github.com/BurntSushi/nfldb/wiki/Windows-Install) pages on the wiki? If you're having trouble with those steps, where exactly did you get hung up?

Without any sort of details, we're going to have a very hard time helping.
