### ISSUE TITLE
NFL Schedule - 2016

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#220]
Can anyone help with getting the 2016 schedule?  When I run it, it comes back with only the PRE games.

**Comment by digitsinmotion** [comment]
I'm actually not able to pull the preseason games scores. 
```
games = nflgame.games(2016, 1, kind="PRE")
TypeError: 'NoneType' object is not iterable
```

I'm new to the nflgame project - is there something I need to run to update the schedule to include these 2016 preseason games? I can pull the 2015 ones just fine.

**Comment by ochawkeye** [comment]
What do you see if you run the following from a command prompt or terminal window?

```bash
python -c "import nflgame; print nflgame.live._CUR_SCHEDULE"
```
If it is `http://www.nfl.com/liveupdate/scorestrip/ss.xml` then I think you'd be seeing the 6 games played in week 1.  (There was also an unplayed game in week 0).

If instead you are seeing `http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml` then `nflgame` is checking the wrong URL for the pre- and regular-season schedule.  There is a [pr](https://github.com/BurntSushi/nflgame/pull/205) to rectify this but @BurntSushi needs to merge it yet.

In file `nflgame/live.py` if you comment out [line 73](https://github.com/BurntSushi/nflgame/blob/master/nflgame/live.py#L73) and uncomment [line 68](https://github.com/BurntSushi/nflgame/blob/master/nflgame/live.py#L68) you should then be able to run `update_sched.py --year 2016` in your `nflgame` site-packages directory.

```bash
C:\Users\Ben>python d:\Python27\Lib\site-packages\nflgame\update_sched.py --year 2016
Last updated: 2016-08-12 13:01:19.289000
Updating (2016, PRE, 0)...
Updating (2016, PRE, 1)...
Updating (2016, PRE, 2)...
Updating (2016, PRE, 3)...
Updating (2016, PRE, 4)...
Updating (2016, REG, 1)...
Updating (2016, REG, 2)...
Updating (2016, REG, 3)...
Updating (2016, REG, 4)...
Updating (2016, REG, 5)...
Updating (2016, REG, 6)...
Updating (2016, REG, 7)...
Updating (2016, REG, 8)...
Updating (2016, REG, 9)...
Updating (2016, REG, 10)...
Updating (2016, REG, 11)...
Updating (2016, REG, 12)...
Updating (2016, REG, 13)...
Updating (2016, REG, 14)...
Updating (2016, REG, 15)...
Updating (2016, REG, 16)...
Updating (2016, REG, 17)...
Updating (2016, POST, 1)...
Updating (2016, POST, 2)...
Updating (2016, POST, 3)...
Updating (2016, POST, 4)...
```

**Comment by ochawkeye** [comment]
@mesee298 

How are you trying to view the regular season games that have not been played yet?

[This conversation](https://github.com/BurntSushi/nflgame/issues/134) dove into how to view games that have not yet started yet in `nflgame`.

[This](https://gist.github.com/ochawkeye/27d208e950fb37beb8fe8107e0d9d35e) sample shows games that have (there aren't any of course) and have not yet been played in week 1 of the regular season, 2016.

**Comment by npinciak** [comment]
for the life of me i couldnt figure out why i couldnt pull this season's preseason stats. totally thought i was doing something wrong, thanks for the insight on the updates @ochawkeye

**Comment by digitsinmotion** [comment]
@ochawkeye You're awesome. Thanks so much. That indeed fixed it.

**Comment by Kirkman** [comment]
That was lifesaving advice, @ochawkeye. Thanks.

**Comment by digitsinmotion** [comment]
Hey @ochawkeye , do you know if there is a way to update this URL in the module via python? Long story short, I'm unable to edit the module directly on my server (GoDaddy shared linux) and need to get that 2016 schedule in there.

**Comment by ochawkeye** [comment]
@digitsinmotion You're unable to modify a file on your server, but you can successfully run `nflgame` that in essence modifies files on your server?  A python package you presumably installed (`nflgame` isn't included by default in any Linux distros I'm aware of...yet :P) has more permissions on your server than you do?

Maybe I'm just not following...

Seems like a weird code challenge, but one way to do this via Python:

```python
with open('path/to/your/nflgame/live.py', 'rb') as f:
	contents = f.read()

contents = contents.replace('# _CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/ss.xml"', '_CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/ss.xml"')
contents = contents.replace('_CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml"', '# _CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml"')

with open('path/to/your/nflgame/live.py', 'wb') as f:
	f.write(contents)
```

Please, I'm begging you.  Don't actually try to do something like this :D

**Comment by digitsinmotion** [comment]
Well, long story short, I don't have shell access - just ftp. Everything has to be done via putting python scripts on the server and running them through php. The big catch to the FTP is I can't access the directory where the module files are being stored, but your idea is a perfect work around.

It's a development environment so if anything messes up - no worries, I can just uninstall and reinstall. Thanks!

**Comment by BurntSushi** [comment]
This should be fixed.
