### ISSUE TITLE
Is yardline...correct? Or am I just reading it wrong?

### ISSUE THREAD

**Issue by flipperbw** [BurntSushi/nflgame#223]
Here's an example play I'm seeing in the database:

`                                                                  description                                                                   |  gsis_id   | play_id | rushing_att | rushing_twopta | rushing_tds | rushing_yds |   time   | yardline`
`(9:49) J.Charles left end for 4 yards, TOUCHDOWN.                                                                                              | 2009112909 |    2427 |           1 |              0 |           1 |           4 | (Q3,311) | (46)`

You can see here Jamaal runs for a 4 yard touchdown. This struck me as strange, since the yardline claims (46). Digging deeper, they were as expected actually on the 4 yard line (http://www.nfl.com/gamecenter/2009112909/2009/REG12/chiefs@chargers_7_2_5/coverage#menu=drivechart%7CcontentId%3A09000d5d814a930a&tab=analyze&analyze=playbyplay). 

Is this just a mistake, or is there some other way to read this (aggregated, perhaps)? If so to the latter, how can I know with certainty where exactly on the field they were at the time of the play?

Thanks.

**Comment by ochawkeye** [comment]
What does your code look like to present the yardline as "`(46)`"?  Or are you looking directly in the `nfldb` PostgreSQL database? (In which case this is more of an `nfldb` question than it is an `nflgame` question).

The `(46)` yard line is offset relative to midfield.  So when it gets accessed, you should be seeing `OPP 4' based on this [code](https://github.com/BurntSushi/nflgame/blob/6278835f10c83c76dbb855c6594ae11353877bf0/nflgame/game.py#L82-L88).

That's what I see on my side:
```python
import nflgame
games = nflgame.games(year=2009, week=12, home='KC', away='KC')
plays = nflgame.combine_plays(games).filter(rushing_tds=True)
for play in plays:
    print play.yardline, play
```
```
OPP 1 (SD, KC 1, Q2, 1 and 1) (10:09) L.Tomlinson right tackle for 1 yard, TOUCHDOWN.
OPP 3 (SD, KC 3, Q3, 1 and 3) (13:02) L.Tomlinson up the middle for 3 yards, TOUCHDOWN.
OPP 4 (KC, SD 4, Q3, 1 and 4) (9:49) J.Charles left end for 4 yards, TOUCHDOWN.
```

**Comment by flipperbw** [comment]
I'm dumb, it's distance from the 50. I figured it would just say (4). Thanks for the help.
