### ISSUE TITLE
Error when running nflgame-update-players

### ISSUE THREAD

**Issue by 4score** [BurntSushi/nflgame#227]
Hello guys,

i ran the command: `sudo nflgame-update-players` and it seems to be failing with the error below. I posted all terminal output:

Loading games for POST 2015 week 5
Downloading team rosters...
32/32 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
5/5 complete. (100.00%)
Done!

There were some errors during the download. Usually this is a
result of an HTTP request timing out, which means the
resulting "players.json" file is probably missing some data.
An appropriate solution is to re-run the script until there
are no more errors (or when the errors are problems on 
NFL.com side.)
-------------------------------------------------------------------------------
Could not get player info from roster row:

<tr class="odd">
<td>75</td>
<td style="text-align:left"> <a href="/player/geralddixonjr./2556427/profile">Dixon, Gerald, Jr.</a></td>
<td>DT</td>
<td>RES</td>
<td> 6'2"</td>
<td>325</td>
<td>3/30/1993</td>
<td>0</td>
<td>South Carolina</td></tr>

Exception:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nflgame/update_players.py", line 419, in run
    roster.append(meta_from_soup_row(team, row))
  File "/usr/lib/python2.7/site-packages/nflgame/update_players.py", line 179, in meta_from_soup_row
    last_name, first_name = map(lambda s: s.strip(), name.split(','))
ValueError: too many values to unpack

-------------------------------------------------------------------------------
Could not get roster for team JAC
-------------------------------------------------------------------------------
Could not get roster for team STL
-------------------------------------------------------------------------------
Could not get GSIS id at http://www.nfl.com/player/justinberger/2557630/profile
-------------------------------------------------------------------------------
Could not find gsis_id for {'status': u'ACT', 'last_name': u'Berger', 'weight': 198, 'profile_id': 2557630, 'number': 8, 'height': 74, 'college': u'Wyoming', 'full_name': u'Justin Berger', 'first_name': u'Justin', 'years_pro': 0, 'birthdate': u'11/22/1991', 'team': 'IND', 'position': u'WR', 'profile_url': 'http://www.nfl.com/player/justinberger/2557630/profile'}

It seems to be failing in a couple places. Any one else running into this problem?

**Comment by ochawkeye** [comment]
Paging @BurntSushi.  Paging @BurntSushi.  @BurntSushi, please accept some of the outstanding pull requests...  @BurntSushi, please accept some of the outstanding pull requests...

https://github.com/BurntSushi/nflgame/pull/219
https://github.com/BurntSushi/nflgame/pull/224
https://github.com/BurntSushi/nflgame/pull/205

**Comment by rjbks** [comment]
The could not get roster for team errors are because the team abbreviations have changed on nfl.com.
The fix is just changing the the team abbreviations in the nflgame module init.py teams list:
Change the first element in the list for each team...
from JAC to JAX and from STL to LA

I could not reproduce you GSIS id error, so can't help you there.

**Comment by BurntSushi** [comment]
This error should no longer be happening because NFL.com fixed it.
