### ISSUE TITLE
Full HTML Page Display of Live Updates

### ISSUE THREAD

**Issue by donlaur** [BurntSushi/nflgame#231]
Does anyone have a full HTML page display of game updates?  Either live and maybe refreshing every 15 seconds, or an offline version that shows play by play, or maybe a full game boxscore in HTML?

Just wondering.  Or does everyone pull down in CSV and use for data modeling?

**Comment by BurntSushi** [comment]
If you just want an HTML display, why not use NFL.com?

**Comment by donlaur** [comment]
The goal being stat based fantasy display where I can also display live
current results and fantasy scoring for yahoo season redraft, yahoo daily,
fanduel, draftkings, etc.  You need the raw stats then you could parse them
and calculate fantasy points based off of scoring, league scoring in season
long redraft cases.
