### ISSUE TITLE
ImportError: No module named nflgame

### ISSUE THREAD

**Issue by AndyReifman** [BurntSushi/nflgame#233]
Alright, so I've installed using
`pip install nflgame`

Just to make sure I was using the right version of python when I issue `python --version` I get `Python 2.7.11`

However I'm getting the `ImportError: No module named nflgame` error. Both when I create a .py file, and if I try to just run it in python.

```
root:~# python
Python 2.7.11 (default, Sep  7 2016, 22:22:41)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nflgame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named nflgame

```

Similarly if I try to just do `nflgame-update-players` I get `nflgame requires Python 2.6+ and does not yet work with Python 3 You are running Python version 3.5` But by looking in my /bin/ folder I can see that `python` is an alias for `python2` which is an alias for `python2.7`

Any suggestions?

**Comment by BurntSushi** [comment]
That error message is *definitive* and means your environment is doing something you don't expect. That error message is produced from this code:

```
if sys.version_info[0] != 2 or sys.version_info[1] < 6:
    print("nflgame requires Python 2.6+ and does not yet work with Python 3")
    print("You are running Python version {}.{}".format(
        sys.version_info.major, sys.version_info.minor))
    sys.exit(1)
```

I don't know what's wrong with your setup, but it appears you *installed* `nflgame` using Python 3.5. Perhaps you use `pip` instead of `pip2.7` or `pip2`? I don't know.

**Comment by ochawkeye** [comment]
While I do not doubt that `python` does in fact appear to be aliased to `python2`/`python27`, I suspect plain old `pip` is not aliasing to what you think it's pointing to.

`pip --version` should tell you all you need to know (at least it does for me in Windows)

```
C:\Users\User>pip --version
pip 8.1.2 from d:\python27\lib\site-packages (python 2.7)
```

**Comment by AndyReifman** [comment]
@ochawkeye, @BurntSushi  Good call, looks like it is an issue with pip, I'll give it a try with pip2.7.

Is there a way to uninstall what I've got currently? And do I even need to?

**Comment by BurntSushi** [comment]
`pip uninstall nflgame`

**Comment by AndyReifman** [comment]
Maybe this is stupid, what should I do to change which pip install I have? I can see in `usr/local/bin/` I have a pip, pip3, and pip3.5 All of which give the same information when I run a version.

However if I go through the normal pip install and issue `python get-pip.py` (where python aliases to python2.7) I get:
```
Traceback (most recent call last):
  File "get-pip.py", line 19177, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
```

**Comment by leighlondon** [comment]
Did you compile that version of Python 2.7 yourself? It sounds like it's missing `zlib` because it's custom: https://github.com/pypa/pip/issues/1919

**Comment by AndyReifman** [comment]
Installed `zlib` following the commands suggested in that issue, still getting the same error.

**Comment by AndyReifman** [comment]
Solved the issue. Also had to install HTTPSHandler.
