### ISSUE TITLE
Issue with getting playerid for player in a play

### ISSUE THREAD

**Issue by ToddAtWSU** [BurntSushi/nflgame#235]
I have a script I wrote last year using nflgame and now this year it is breaking and I do not know what I am missing. I wonder if it has to do with a rookie player. I am trying to see if a player made any FGs and I keep breaking on Robert Aguayo. My snippet of code looks like:

```
for play in nflgame.combine_plays(week).filter(kicking_fgm=True):
            for playerInPlay in play.players:
                if playerInPlay.player.player_id == member.playerid:
```
Before the if-statement, if I print playerInPlay it prints R.Aguayo. But when I try to print playerInPlay.player it prints None. So do I need to do something to make sure I have new players added this year? The loop successfully works for the first 2 iterations with G.Gano but when I first hit R.Aguayo it crashes.

Thanks for your help!
Todd

**Comment by BurntSushi** [comment]
Every season, you should upgrade nflgame to the latest version. Doing that alone might fix this. You can also try running `nflgame-update-players`.

Off topic: does the WSU in your username by chance stand for Worcester State University?

**Comment by ToddAtWSU** [comment]
So I am not a Python developer but rather a C/C++ developer. How exactly do I upgrade nflgame? I tried running `nflgame-update-players` in my Python 2.7.11 Shell, but I got the following error.

> NameError: name 'update' is not defined

And no, WSU stands for Wright State University in Ohio.

**Comment by BurntSushi** [comment]
To upgrade: `pip install --upgrade nflgame`.

`nflgame-update-players` isn't Python. It's a CLI program. Run it in your shell/console.

**Comment by ToddAtWSU** [comment]
Thanks so much. I was starting to read your documentation on pip and found the nflgame-update-players script. But thanks for this. It has updated and now to see where my script will break next! :) Thanks again!
