### ISSUE TITLE
Week 1, 2016 data

### ISSUE THREAD

**Issue by cminton** [BurntSushi/nflgame#236]
When I try to get the game data for week 1, 2016, I am getting an error. So, I do:

import nflgame
games = nflgame.games(year=2016, week=1)

I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cminton/anaconda2/lib/python2.7/site-packages/nflgame/__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable

What am I doing wrong?

**Comment by BurntSushi** [comment]
Are you using the latest version of `nflgame`? Please upgrade. `pip install --upgrade nflgame`.

**Comment by cminton** [comment]
Thanks Andrew. That fixed it. Although, I am sure I upgraded in August and everything worked fine as long as I did not pull data for this year.

Anyway, thanks again!

**Comment by BurntSushi** [comment]
Yeah, there was a new release just before the season started.

As a rule of thumb, always make sure you're using the latest version before reporting an issue. You can see releases here: https://pypi.python.org/pypi/nflgame
