### ISSUE TITLE
NFL 2016 season

### ISSUE THREAD

**Issue by kpelechrinis** [BurntSushi/nflgame#237]
I tried to access the games from week 1 but I could not:

import nflgame
games = nflgame.games(2016,week=1,kind="REG")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nflgame-1.2.19-py2.7.egg/nflgame/__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not utterable

Suggestions? Maybe the games are not in Game Center yet (which I doubt since they have live updates)?

**Comment by BurntSushi** [comment]
Please update `nflgame`. To do so, run `pip install --upgrade nflgame`.
