### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by crosss3** [BurntSushi/nflgame#240]
I have installed nflgames using pip on python 2.7. If I try and run just
import nflgames I get this error:
DLL load failed: %1 is not a valid Win32 application

Any help would be appreciated.

Thanks

**Comment by shoesCodeFor** [comment]
I think this an issue with your path  Go into the parent directory of nflgame.  This should be 'site-packages'.  Then try your python command line from there.  If it loads the module then your path is not defined.  I'm not a windows guy but I think this is how you add it.  http://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7
