### ISSUE TITLE
nflgame.combine_max_stats: Worked in 2015, not 2016

### ISSUE THREAD

**Issue by mattmiddione** [BurntSushi/nflgame#241]
I was using this code last year to build a player database of season stats (all games):

import nflgame
season2015 = nflgame.games(2015)
players = nflgame.combine_max_stats(season2015)
QB1 = players.name("A.Dalton")
print '%0s' '%8s' '%6s' '%7s' '%6s' '%7s' '%5s' '%6s' '%7s' % ('Quarterback', 'Att', 'Comp', '%', 'Yds', 'YPC', 'TDs', 'INTs', 'QBR')
print '%0s' '%11.0f' '%6.0f' '%7.1f' '%6.0f' '%7.2f' '%5.0f' '%6.0f' '%7.1f' % (QB1, QB1.passing_att, QB1.passing_cmp, round(100*(float(QB1.passing_cmp)/float(QB1.passing_att)),1), QB1.passing_yds, round(float(QB1.passing_yds)/float(QB1.passing_cmp),1), QB1.passing_tds, QB1.passing_ints, QB1.passer_rating())

Output:
Quarterback     Att  Comp      %   Yds    YPC  TDs  INTs    QBR
A.Dalton        386   255   66.1  3250  12.70   25     7  108.8

However, when I use the same code as above and change the season from 2015 to 2016, I seem to only get information from Andy Dalton's last game (not the entire 4 weeks of the 2016 NFL season):

import nflgame
season2016 = nflgame.games(2016)
players = nflgame.combine_max_stats(season2016)
QB1 = players.name("A.Dalton")
print '%0s' '%8s' '%6s' '%7s' '%6s' '%7s' '%5s' '%6s' '%7s' % ('Quarterback', 'Att', 'Comp', '%', 'Yds', 'YPC', 'TDs', 'INTs', 'QBR')
print '%0s' '%11.0f' '%6.0f' '%7.1f' '%6.0f' '%7.2f' '%5.0f' '%6.0f' '%7.1f' % (QB1, QB1.passing_att, QB1.passing_cmp, round(100*(float(QB1.passing_cmp)/float(QB1.passing_att)),1), QB1.passing_yds, round(float(QB1.passing_yds)/float(QB1.passing_cmp),1), QB1.passing_tds, QB1.passing_ints, QB1.passer_rating())

Output:
Quarterback     Att  Comp      %   Yds    YPC  TDs  INTs    QBR
A.Dalton         31    22   71.0   296  13.50    1     0  111.8

Any insight as to what changed from 2015 to 2016? Thanks!

**Comment by mattmiddione** [comment]
Does anyone have any insight? Thanks!

**Comment by ochawkeye** [comment]
Seems to work just fine for me.  

```
2015
Quarterback     Att  Comp      %   Yds    YPC  TDs  INTs    QBR
A.Dalton        386   255   66.1  3250  12.70   25     7  108.8
2016
Quarterback     Att  Comp      %   Yds    YPC  TDs  INTs    QBR
A.Dalton        146    97   66.4  1234  12.70    3     2   93.8
```

Make sure you're running the latest version of nflgame?
`pip install --upgrade nflgame`

(By the way, if you "fence" in your code with 3 tick marks ` it will present nicely in github.)

**Comment by mattmiddione** [comment]
Thanks for the response. I ran the command to upgrade nflgame:

pip install --upgrade nflgame
Requirement already up-to-date: nflgame in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Collecting pytz (from nflgame)
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 481kB 1.2MB/s 
Collecting httplib2 (from nflgame)
  Downloading httplib2-0.9.2.zip (210kB)
    100% |████████████████████████████████| 215kB 1.4MB/s 
Requirement already up-to-date: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from nflgame)
Installing collected packages: pytz, httplib2
  Found existing installation: pytz 2015.4
    Uninstalling pytz-2015.4:
      Successfully uninstalled pytz-2015.4
  Found existing installation: httplib2 0.9.1
    Uninstalling httplib2-0.9.1:
      Successfully uninstalled httplib2-0.9.1
  Running setup.py install for httplib2 ... done
Successfully installed httplib2-0.9.2 pytz-2016.7

It looks like I was already using the latest version? I still get the same stats (results from the last game they played):

```OFFENSE
Quarterback     Att  Comp      %   Yds    YPC  TDs  INTs    QBR
A.Dalton         31    22   71.0   296  13.50    1     0  111.8
D.Carr           35    25   71.4   199   8.00    4     0  123.4

(thanks for the insight on formatting code for github)

**Comment by ochawkeye** [comment]
How many games do you have in `season2016`?

```
>>> print len(season2016)
64
```

**Comment by mattmiddione** [comment]
I get 16 games when I do that.

**Comment by mattmiddione** [comment]
I did an uninstall and then re-installed and everything is working fine. Thanks for your input!
