### ISSUE TITLE
Question: How did you find out about the various endpoints?

### ISSUE THREAD

**Issue by delta25** [BurntSushi/nflgame#245]
API's great, but I'm just a bit curious to know how you found out about the possible endpoints, such as

- http://www.nfl.com/liveupdate/game-center/xxx/xxx_gtd.json
- http://www.nfl.com/liveupdate/scorestrip/ss.xml
- http://www.nfl.com/schedules/yyyy/www

Was there a list somewhere, or did you monitor where requests went on the front facing site?

Thanks :)

**Comment by BurntSushi** [comment]
There's no list. They are undocumented. I found them using the standard Javascript/HTTP development tools that come with Google Chrome.

**Comment by donlaur** [comment]
You can find out end URL's using something like Postman and Postman
Interceptor.

**Comment by delta25** [comment]
Yep that's what I was doing before I found this. And I had identified the request for the individual game stuff, and the current week's scorestrip.

It's this one http://www.nfl.com/ajax/scorestrip?&season=2016&seasonType=REG&week=1 which remains a complete mystery. I just can't figure out which of the pages on nfl.com send a request to it. Again, just a matter of being curious. I mean hell, you can go all the way back to 1966 with that thing.

**Comment by BurntSushi** [comment]
You definitely don't need any additional tools. Just open "developer tools" in Google Chrome and click the "Network" tab. Then click the "XHR" filter.

I don't know the precise pages I visited. It was 4 or 5 years ago at this point.
