### ISSUE TITLE
Documentation for meaning of the various stats keys?

### ISSUE THREAD

**Issue by houbysoft** [BurntSushi/nflgame#248]
Hi,

is there any documentation regarding what the stats keys like these mean:

```
...
 u'punting_avg',
 u'punting_i20',
 u'punting_lng',
 u'punting_pts',
 u'punting_yds',
 u'puntret_avg',
 u'puntret_lng',
 u'puntret_ret',
 u'puntret_tds',
 u'receiving_lng',
 u'receiving_rec',
 u'receiving_tds',
 u'receiving_twopta',
 u'receiving_twoptm',
 u'receiving_yds',
 u'rushing_att',
 u'rushing_lng',
 u'rushing_tds',
 u'rushing_twopta',
...
```

I'm trying to calculate the average fantasy points per game for Andrew Luck after the 5 games of the 2016 season, as computed by DraftKings, but I think I must be using the wrong keys because I'm not getting the right answer according to them. They think it's `22.5`:

![screen shot 2016-10-15 at 12 12 42 am](https://cloud.githubusercontent.com/assets/212043/19408186/277744b8-926c-11e6-8068-3e8de8e74c05.png)

I currently have [some code](https://gist.github.com/houbysoft/ad9704cf1bdb951c8d37e02c5176ead5) that tries to recompute this `22.5`, but I'm getting `24.332`, and that's even before implementing the bonuses for 300+ yard passing games, 100+ yard rushing & receiving games so there must be something wrong in my calculation.

For reference, I'm going off this description of the scoring system that DraftKings has:

```
Offensive players will accumulate points as follows:
Passing TD = +4PTs
25 Passing Yards = +1PT (+0.04PT/ per yard is awarded)
300+ Yard Passing Game = +3PTs
Interception = -1PT
10 Rushing Yards = +1PT (+0.1PT per yard is awarded)
Rushing TD = +6PTs
100+ Yard Rushing Game = +3PTs
10 Receiving Yards = +1PT (+0.1PT per yard is awarded)
Reception = +1PT
Receiving TD = +6PTs
100+ Yard Receiving Game = +3PTs
Punt/Kickoff Return/FG Return for TD = +6PTs
Fumble Lost = -1PT
2 Point Conversion (Pass, Run, or Catch) = +2PTs
Offensive Fumble Recovery TD = +6PTs
```

Any ideas?
Thanks!

**Comment by houbysoft** [comment]
Oh, I should also probably say that to get the player object to pass into my function I did this:

```
players_2016 = nflgame.combine(nflgame.games(2016))
aluck = filter(lambda p: p.name == 'A.Luck', players_2016)[0]
```

**Comment by ochawkeye** [comment]
https://github.com/BurntSushi/nflgame/wiki/Stat-types

**Comment by ochawkeye** [comment]
I haven't run your code, but looks like you're deducting points for a stat category `passing_ints`.  I think the category should actually be `passing_int`

**Comment by ochawkeye** [comment]
This one is contributing to your error:
```
    # Offensive Fumble Recovery TD +6 PTs
    score += 6.00 * value_or_zero(p, 'fumbles_trcv')
```

Those are total fumbles recovered, NOT fumbles recovered for touchdowns.

FYI, instead of your `value_or_zero` function, you can take advantage of the fact that the player stats is a dictionary itself.

`score += 4.00 * value_or_zero(p, 'passing_tds')`
is equivalent to
`score += 4.00 * p.stats.get('passing_tds', 0)`

**Comment by houbysoft** [comment]
Awesome, thank you! Not sure how I missed that link because I did try searching some of the key names.

In any case, looks like the fumbles_trcv was indeed the problem. I'm now getting correct values :)
