### ISSUE TITLE
Add Hacktoberfest Label

### ISSUE THREAD

**Issue by DanielJMaher** [BurntSushi/nflgame#254]
Can you add a Hacktoberfest Label so we can get credit for PRs? @BurntSushi

**Comment by ochawkeye** [comment]
Rules state "Pull requests can be made in any GitHub-hosted repositories/projects." 

Are you sure an explicit label is required of the repo?

**Comment by DanielJMaher** [comment]
My mistake, I misread "Submit four pull requests to win a free T-shirt. Browse issues labeled "Hacktoberfest" on GitHub for other projects."  I'm just going to go ahead and close this.
