### ISSUE TITLE
Week 9 2016 DEN vs OAK showing wrong meridien time

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#258]
If you go to http://www.nfl.com/ajax/scorestrip?season=2016&seasonType=REG&week=9, you can see the following:
<g eid="2016110600" gsis="57032" d="Sun" t="8:30" q="P" k="" h="OAK" hnn="raiders" hs="" v="DEN" vnn="broncos" vs="" p="" rz="" ga="" gt="REG"/>

But if you run update_sched.py --rebuild you get:
   "2016110600",
   {
    "away": "DEN",
    "day": 6,
    "eid": "2016110600",
    "gamekey": "57032",
    "home": "OAK",
    **"meridiem": "AM",**
    "month": 11,
    "season_type": "REG",
    "time": "8:30",
    "wday": "Sun",
    "week": 9,
    "year": 2016

It should be PM, but the json shows AM.  What am I doing wrong?

**Comment by ochawkeye** [comment]
NOTE: We're actually talking about week 9 here...

You're not doing anything wrong.  In all cases in the past, the `.eid` has been in chronological order for the week.  The first game of the day was always `########00`.  The second game of the day was `########01`.  The third game of the day was `########02`.  

For some unknown reason, the NFL has assigned the eid for the _last_ Sunday game this week as `2016110600`.  Since nflgame [thinks](https://github.com/BurntSushi/nflgame/blob/master/nflgame/update_sched.py#L80-L109) its the first game of the day, and sees that there are games after it with "earlier" times, it assumes that it is an AM game.

**Comment by ochawkeye** [comment]
Just to clarify one point...the week 9 schedule link you posted does not give any hints to whether or not the game is AM or PM.  It list only that the game starts on Sunday at "8:30".  The `q="P"` designates that the game is in "Pregame" as opposed to `q="F"` (Final) or `q="FO"` (Final Overtime)`.  

Notice in [week 8](http://www.nfl.com/ajax/scorestrip?season=2016&seasonType=REG&week=8) that the game in London that kicked off at 9:30 am (2016103000) doesn't have any clues that it was a morning game.

nflgame is attempts to guess whether the game is in the morning based on the other games being played that day.

Worth noting in case this becomes a recurring problem in the future and not just a one-off wonky eid from the NFL.  It does look like in this case, that the `gsis_id`s for the week do remain in chronological order despite the `eid`s getting shuffled.

**Comment by weixiyen** [comment]
Hmmm, could we simply have the start time comparison use the gsis key instead of eid?

I can submit a patch if that is something that could work.

**Comment by ochawkeye** [comment]
Maybe. Probably want to back test it against history before jumping into the change. 

I'm of the opinion that the NFL just screwed up the EID in this case.  Would be just as easy for them to screw up the order of the GSIS gamekey in the past or the future and then we're in the same boat.

**Comment by ochawkeye** [comment]
Taking a quick glance at 2016:  weeks 1-7 and 10-17 all look to be in chronological order, but it looks like our week 9 is not the only case where the eid it wacky.

Week 8 also had a case where the eids were not ordered properly.
```
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57008', u'season_type': u'REG', u'away': u'JAX', u'year': 2016, u'month': 10, u'eid': u'2016102700', u'time': u'8:25', u'home': u'TEN', u'wday': u'Thu', u'day': 27}
{u'week': 8, u'meridiem': u'AM', u'gamekey': u'57009', u'season_type': u'REG', u'away': u'WAS', u'year': 2016, u'month': 10, u'eid': u'2016103000', u'time': u'9:30', u'home': u'CIN', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57010', u'season_type': u'REG', u'away': u'GB', u'year': 2016, u'month': 10, u'eid': u'2016103001', u'time': u'4:25', u'home': u'ATL', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57011', u'season_type': u'REG', u'away': u'NE', u'year': 2016, u'month': 10, u'eid': u'2016103002', u'time': u'1:00', u'home': u'BUF', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57012', u'season_type': u'REG', u'away': u'NYJ', u'year': 2016, u'month': 10, u'eid': u'2016103003', u'time': u'1:00', u'home': u'CLE', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57013', u'season_type': u'REG', u'away': u'DET', u'year': 2016, u'month': 10, u'eid': u'2016103004', u'time': u'1:00', u'home': u'HOU', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57014', u'season_type': u'REG', u'away': u'KC', u'year': 2016, u'month': 10, u'eid': u'2016103005', u'time': u'1:00', u'home': u'IND', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57015', u'season_type': u'REG', u'away': u'SEA', u'year': 2016, u'month': 10, u'eid': u'2016103006', u'time': u'1:00', u'home': u'NO', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57016', u'season_type': u'REG', u'away': u'OAK', u'year': 2016, u'month': 10, u'eid': u'2016103007', u'time': u'1:00', u'home': u'TB', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57017', u'season_type': u'REG', u'away': u'SD', u'year': 2016, u'month': 10, u'eid': u'2016103008', u'time': u'4:05', u'home': u'DEN', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57018', u'season_type': u'REG', u'away': u'ARI', u'year': 2016, u'month': 10, u'eid': u'2016103009', u'time': u'1:00', u'home': u'CAR', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57019', u'season_type': u'REG', u'away': u'PHI', u'year': 2016, u'month': 10, u'eid': u'2016103010', u'time': u'8:30', u'home': u'DAL', u'wday': u'Sun', u'day': 30}
{u'week': 8, u'meridiem': u'PM', u'gamekey': u'57020', u'season_type': u'REG', u'away': u'MIN', u'year': 2016, u'month': 10, u'eid': u'2016103100', u'time': u'8:30', u'home': u'CHI', u'wday': u'Mon', u'day': 31}
```

Notice game 2016103001.  In that case, the GSIS (`gamekey`) was also incorrectly ordered.  That one did not present itself as an issue because of the [rule](https://github.com/BurntSushi/nflgame/blob/master/nflgame/update_sched.py#L83) that any game before "6:00" is probably `PM`.

**Comment by weixiyen** [comment]
I see... perhaps the real long-term fix is to use actual gsis data on nflgsis.com

We can mimick the browser, do a request for the authentication token.  Then using that connect to the websocket to get the schedule.  That one does include meridiem information:

<img width="266" alt="screenshot 2016-11-02 12 18 43" src="https://cloud.githubusercontent.com/assets/59597/19943904/ad08fad4-a0f6-11e6-8615-01ac059bb806.png">

**Comment by mesee298** [comment]
So, basically what you are saying is that cannot be fixed, and I manually have to make that change from AM to PM, correct?

**Comment by weixiyen** [comment]
@mesee298 You can change eid to gamekey on these 2 lines and it should work for all games this season, but it does not gaurantee anything for the future based on the way the detection works.

https://github.com/BurntSushi/nflgame/blob/master/nflgame/update_sched.py#L89

**Comment by mesee298** [comment]
@weixiyen  That would be fine if I didn't run the update_sched.py everyday (due to potential flex games).  I've coded around it.  Thanks for your suggestion.
