### ISSUE TITLE
Is is possible to get usage rate and snap counts per game?

### ISSUE THREAD

**Issue by 4score** [BurntSushi/nflgame#264]
Hi guys,

Was wondering if it was possible to get usage rates on a per game basis? I was looking at the drives raw output and was thinking that it may not be possible. Is there another way?

Thanks for your time!

**Comment by BurntSushi** [comment]
What is "usage rate"?

**Comment by 4score** [comment]
Hello,

Maybe adding "usage rate" in the title was a bit redundant since snap counts is mainly what i'm after. Basically just the amount of snaps a player was involved in out of the total number of snaps for the team. 

Thanks again!

**Comment by BurntSushi** [comment]
Nope, there's no way. Only statistical events are reported. This means that information on positions that rarely record stats is hard to get.
