### ISSUE TITLE
Inconsistent stats per week using combine_max_stats?

### ISSUE THREAD

**Issue by lchu122** [BurntSushi/nflgame#272]
I was working with combine_max_stats to get weekly stat lines and I wanted to gather a dataframe of players across multiple weeks. However, I encountered mismatches of number of values vs number of columns. Testing the length I found out the number of stats vary from each week.  For example, after taking a set difference of the weeks 1-3 for 2009:
```
1 and 2: set(['defense_misc_yds', 'fumbles_rec_tds', 'defense_puntblk', 'punting_blk', 'defense_misc_tds'])
2 and 3: set(['defense_safe', 'defense_xpblk', 'rushing_twoptmissed', 'defense_frec_tds'])
1 and 3: set(['fumbles_rec_tds', 'defense_safe', 'rushing_twoptmissed', 'defense_frec_tds'])
```
Anyone encounter this issue? What was your workaround?

**Comment by ochawkeye** [comment]
Stat categories with a value of 0 aren't included in your stats, so that's why you see a mismatch.  (ie. If there were no extra points blocked in a week, then the category `defense_xpblk` isn't going to be included in that weeks stats)

I _think_ there is an `allfields=True` flag you can use to get all stat categories included, but that might be a csv thing.

**Comment by lchu122** [comment]
@ochawkeye that totally makes sense, and yeah using allfields = True works!  Side question: what other parameters are there for .csv method for the object produced by combine_max_stats()? There isn't documentation for it and I'm not quite sure how to dig into it (reading up on inspect and pydoc right now). I'm specifically looking if it has a parameter for append.

**Comment by ochawkeye** [comment]
I think `allfields` is the only parameter available for that method.  [source](https://github.com/BurntSushi/nflgame/blob/17f2f866302383adaef6c73b00483ddf64263e6c/nflgame/seq.py#L286)

```python
    def csv(self, fileName, allfields=False):
        """
```

Appending would probably be an easy enough feature to add, but without some deep analysis of what is already in the file, I'm don't think it would be capable of avoiding adding the same data already contained it the file.

Short of a pull-request to introduce an append feature, you might have to roll your own.  Something like this:

```python
import nflgame
import csv
import os

def append_to_csv_file(full_file, small_file):
    with open(full_file, 'ab') as season_file:
        w = csv.writer(season_file)

        with open(small_file, 'rb') as week_file:
            r = csv.reader(week_file)

            for row in r:
                w.writerow(row)

FULL_SEASON_FILE = '2016-season.csv'  # this is empty right now

games = nflgame.games(2016, week=1, kind='REG')
nflgame.combine(games).csv('2016-week01.csv', allfields=True)
append_to_csv_file(FULL_SEASON_FILE, '2016-week01.csv')

print os.stat(FULL_SEASON_FILE).st_size

games = nflgame.games(2016, week=2, kind='REG')
nflgame.combine(games).csv('2016-week02.csv', allfields=True)
append_to_csv_file(FULL_SEASON_FILE, '2016-week02.csv')

print os.stat(FULL_SEASON_FILE).st_size
```

The file size in bytes after each week.
```
130266
268758
```

It would be up to you though to ensure you're not adding redundant data to your "full" file.

**Comment by lchu122** [comment]
@ochawkeye This pretty much wraps my question up. Much appreciated for the fast responses, thanks a lot!

**Comment by lchu122** [comment]
forgot to post this but fyi, the max stats categories  w/  allfields = True changes even within a year, (in year 2009 defense misc yards doesnt appear in some of the weeks as a stat line), so currently I'm just storing values into a pandas data frame every week to ensure the stats match up properly.
