### ISSUE TITLE
Getting disqualified (ejected) players

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#276]
Can you provide the easiest way to show what players that were disqualified (ejected) from a game.  

For example: Jordan Reed - Washington was disqualified on the Monday game.  

nflgame.games(year=2016, week=15, kind='REG')
Player = "J.Reed"

**Comment by snake-plissken** [comment]
This information is in the description of a play.  You could access this by first getting the drives of a game and then going through each play of the drive and checking the desc fields of each play.  My apologies for bastardizing the API (I use nfldb more often) but I couldn't figure out how to extract the desc field without basically undoing all of the iterator objects.

```
games = nflgame.games(year=2016, week=15, kind='REG')
drives = [list(x.drives) for x in games]
play_container = []
#Double loop because drives is a list containing lists of Drive objects
for entry in drives:
    for drive in entry:
        drive_play_list = list(drive.plays)
        play_container.append(drive_play_list)

#play_container is a list, containing lists of each drive's Play objects
```

In this specific case, It looks like identifier is "disqualified" so for each play, you'd need to do something similar to:

```
if single_play.desc.find("disqualified") != -1:
    #found a play where someone was ejected, do stuff
```

The value of desc for the Jordan Reed punch is:

> (:36) R.Kelley left end to CAR 12 for -2 yards (A.Klein, K.Short). PENALTY on WAS-J.Reed, Unnecessary Roughness, 15 yards, enforced at CAR 12. 86-Reed is disqualified.  

Also, it looks like there is not a standard string that is used to indicate when an ejection happens.  I've found the following strings have been used so far, in 2016 at least:

- Disqualification
- Disqualified
- disqualified
- Ejection, EJECTED, ejection (but never without one of the above three also being used)

If you have nfldb installed, you can query the plays table to get the plays where a player was disqualified:
`SELECT * FROM plays WHERE description like '%disqual%';`

**Comment by mesee298** [comment]
Okay, so I've installed NFLDB, and I can see you can pull this from the description, but how do you associate that to a play?
