### ISSUE TITLE
2016 Post season Error

### ISSUE THREAD

**Issue by andrewvandenheuvel** [BurntSushi/nflgame#283]
I am able to get previous year post seasons, but not the current 2016/2017 games being played now.
```
`#!/us/bin/python2.7

import nflgame
k = nflgame.games(2017, kind='POST')
for game in k:
    print game`
```

I get error:

````
/usr/bin/python2.7 /root/PycharmProjects/untitled/test.py
Traceback (most recent call last):
  File "/root/PycharmProjects/untitled/test.py", line 4, in <module>
    k = nflgame.games(2017, kind='POST')
  File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 229, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1
````

I am running this as root, not ideal, but running as myslef gives me nflgame 

````ImportError: No module named nflgame````

**Comment by ochawkeye** [comment]
The schedule URL on nfl.com changes for the postseason. You'll either need to 'git pull' the latest version of 'nflgame' or change the URL in live.py.

**Comment by andrewvandenheuvel** [comment]
I've changed live.py my commenting out the first line and uncommenting the last as follows:
```
#_CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/ss.xml"
# """
# Pinged infrequently to discover the current week number, year and week type.
# The actual schedule of games is taken from the schedule module.
# """
_CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml"
```
This didn't work. I also did a `git clone https://github.com/BurntSushi/nflgame.git`
and `python setup.py Makefile` and I'm not having any luck.

Is there something else I can try?

**Comment by ochawkeye** [comment]
Sorry, I only got you halfway there...

After changing the URL in `live.py`, run `update_sched.py` (found in `/nflgame`).  That will go out, find new games in the schedule and add them to `schedule.json`.

**Comment by andrewvandenheuvel** [comment]
That was it, thank you.
