### ISSUE TITLE
Change in team abbr from JAC to JAX creates integrity error in nfldb update

### ISSUE THREAD

**Issue by MargareeMan** [BurntSushi/nflgame#295]
the latest nfldb.sql file is 2016-09-08.  When I ran the the nfldb-update script it failed (see attached file) during the bulk insert processing.

[JAX key integrity update errors 2017-03-20.txt](https://github.com/BurntSushi/nflgame/files/856877/JAX.key.integrity.update.errors.2017-03-20.txt)

I do not know how to intercept the JAX abbr and alter it to JAC.  Running python code to create .csv schedule files gives JAC for 2015 but JAX for 2016.

**Comment by TomMcCabe** [comment]
Wrong repo. You're looking for [nfldb](https://github.com/BurntSushi/nfldb).

The issue you're referring to is [here](https://github.com/BurntSushi/nfldb/issues/194).

**Comment by MargareeMan** [comment]
Thank you.  Please accept my apologies for getting the wrong repo.
