### ISSUE TITLE
game data for 2017 regular season

### ISSUE THREAD

**Issue by nbkincaid** [BurntSushi/nflgame#298]
This project is awesome!

Now that the 2017 regular season schedule is out, at what point will we be able to access the schedule with the following? =>

```
>>> import nflgame
>>> nflgame.games(2017)
[]
```

Thank you!
Nick

**Comment by nbkincaid** [comment]
Or maybe a better question is this => Is there a way to access the full upcoming schedule with the nflgame package?

Thank you!
Nick

**Comment by eckerlycl** [comment]
In file nflgame/live.py if you comment out line 73 and uncomment line 68 you should then be able to run update_sched.py --year 2017 in your nflgame site-packages directory.

**Comment by derek-adair** [comment]
The work-a-round is nice to have but how might I write this in a maintainable way?

Do I fork this project and leave ln 73 out and 68 in for live.py?

**Comment by derek-adair** [comment]
Also this isn't working for me.  I can see the games in nflgame.sched.games as well as schedule.json... however nflgame.games(2017) is not working for me.

**Comment by ochawkeye** [comment]
`nflgame.games` only looks at games that have already taken place.

My schedule has only the first game of the preseason currently in it after running the `nflgame-update-schedule` script.

```python
import nflgame

year = 2017
week = 0
kind = 'PRE'


past_games = nflgame.games(year=year, week=week, kind=kind)
for game in past_games:
    print game

print '-'

future_games = [game for game in nflgame.live._games_in_week(year=year, week=week, kind=kind) if game['eid'] not in [g.eid for g in past_games]]
for game in future_games:
    print '{} at {} on {}/{} {}'.format(game['away'], game['home'], game['month'], game['day'], game['time'])
```
```
-
DAL at ARI on 8/3 8:00
[Finished in 0.7s]
```

**Comment by derek-adair** [comment]
I see. Whats the best way to access the upcoming games?

**Comment by ochawkeye** [comment]
As far as I can tell, the NFL hasn't updated the schedule page we use yet.

http://www.nfl.com/liveupdate/scorestrip/ss.xml

**Comment by derek-adair** [comment]
I dont understand why i'm seeing the game data in schedule.json then...

also... the data seems to be in nflgame.sched.games...

```
>>> import nflgame
>>> nflgame.sched.games.popitem()
(u'2017123114', {u'week': 17, u'meridiem': u'PM', u'gamekey': u'57488', u'season_type': u'REG', u'away': u'SF', u'year': 2017, u'month': 12, u'eid': u'2017123114', u'time': u'4:25', u'home': u'LA', u'wday': u'Sun', u'day': 31})
```

**Comment by ochawkeye** [comment]
Well, I'll be...

In that case, you should be able to use the code above to view the games week by week:

```python
import nflgame

year = 2017
week = 17
kind = 'REG'


past_games = nflgame.games(year=year, week=week, kind=kind)
for game in past_games:
    print game

print '-'

future_games = [game for game in nflgame.live._games_in_week(year=year, week=week, kind=kind) if game['eid'] not in [g.eid for g in past_games]]
for game in future_games:
    print '{} at {} on {}/{} {}'.format(game['away'], game['home'], game['month'], game['day'], game['time'])
```

**Comment by derek-adair** [comment]
I believe the data is there because i ran

`python update_sched.py --year 2017`

**Comment by derek-adair** [comment]
Could you break down this line for me?  I'm not *THAT* familiar with python ;)

`[game for game in nflgame.live._games_in_week(year=year, week=week, kind=kind) if game['eid'] not in [g.eid for g in past_games]]`

Particularly the first part... [game for game....

I'm assuming this somehow takes the results of the for loop?

**Comment by ochawkeye** [comment]
That's a list comprehension.
```python
even_numbers = [n for n in [0, 1, 2, 3, 4] if n%2 == 0]
print even_numbers
alt_even_numbers = []
for n in [0, 1, 2, 3, 4]:
    if n%2 == 0:
        alt_even_numbers.append(n)
print alt_even_numbers
```
```
[0, 2, 4]
[0, 2, 4]
```

This line:
```python
future_games = [game for game in nflgame.live._games_in_week(year=year, week=week, kind=kind) if game['eid'] not in [g.eid for g in past_games]]
```
can be rewritten as follows:

```python
past_game_eids = []
for g in past_games:
    past_game_eids.append(g.eid)

future_games = []
for game in nflgame.live._games_in_week(year=year, week=week, kind=kind):
    if game['eid'] not in past_game_eids:
        future_games.append(game)
```

**Comment by derek-adair** [comment]
Nice! I could read it and tell what it was doing but it's nice to put the name to it.  Thank you very much for your attention to my questions.

Is there no easy way to pull the entire schedule from 2017 into an object? Just curious.

**Comment by ochawkeye** [comment]
Have you looked at all at [nfldb](https://github.com/BurntSushi/nfldb)?

```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2017, season_type='Regular')
for game in q.as_games():
    print game
```
Prints out every game in the 2017 regular season.

Your query can be further filtered like so:
```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2017, season_type='Regular')
q.game(team='MIN')

for game in q.as_games():
    print game
```
```
Regular 2017 week 1 on 09/11 at 06:10PM, NO (0) at MIN (0)
Regular 2017 week 2 on 09/17 at 12:00PM, MIN (0) at PIT (0)
Regular 2017 week 3 on 09/24 at 12:00PM, TB (0) at MIN (0)
Regular 2017 week 4 on 10/01 at 12:00PM, DET (0) at MIN (0)
Regular 2017 week 5 on 10/09 at 07:30PM, MIN (0) at CHI (0)
Regular 2017 week 6 on 10/15 at 12:00PM, GB (0) at MIN (0)
Regular 2017 week 7 on 10/22 at 12:00PM, BAL (0) at MIN (0)
Regular 2017 week 8 on 10/29 at 08:30PM, MIN (0) at CLE (0)
Regular 2017 week 10 on 11/12 at 12:00PM, MIN (0) at WAS (0)
Regular 2017 week 11 on 11/19 at 12:00PM, LA (0) at MIN (0)
Regular 2017 week 12 on 11/23 at 11:30AM, MIN (0) at DET (0)
Regular 2017 week 13 on 12/03 at 12:00PM, MIN (0) at ATL (0)
Regular 2017 week 14 on 12/10 at 12:00PM, MIN (0) at CAR (0)
Regular 2017 week 15 on 12/17 at 12:00PM, CIN (0) at MIN (0)
Regular 2017 week 16 on 12/23 at 07:30PM, MIN (0) at GB (0)
Regular 2017 week 17 on 12/31 at 12:00PM, CHI (0) at MIN (0)
```

**Comment by derek-adair** [comment]
I've considered it but it seemed unnecessary/additional complication.  I am developing a simple office pool app that requires simple schedule data with win/loss... I'd rather just write a simple script to pull this data than administer a DB I have little understanding of.

Instead I have a very simple psql db and i'm using nflgame to import things once a season.

**Comment by BurntSushi** [comment]
@derek-adair nfldb's database is extremely simple and follows a straight-forward relational model: http://burntsushi.net/stuff/nfldb/nfldb-condensed.pdf

**Comment by derek-adair** [comment]
Sure, i get that.  However, I only need two of those tables (Team/Game) and have quite a bit of other custom junk that I have tacked on for the app.  In the future I will consider making the switch but that requires some changes I'm not prepared to take on in this current round of development.  Also lazy.

**Comment by derek-adair** [comment]
Perhaps i should just take a look at how you are importing games into that database...

ugh it may actually be simpler to figure out how to get this working with my current plan....

**Comment by andr3w321** [comment]
If you don't want a DB and don't mind parsing a little JSON you can check out my espn scraper https://github.com/andr3w321/espn_scraper

```
import espn_scraper as espn

scoreboard_urls = espn.get_all_scoreboard_urls("nfl", 2017)
for scoreboard_url in scoreboard_urls:
    data = espn.get_url(scoreboard_url, cached_path="cached_json")
    week = data['content']['sbData']['week']['number']
    for event in data['content']['sbData']['events']:
        print(event['season']['type'],
              event['season']['year'],
              week,
              event['competitions'][0]['competitors'][0]['team']['abbreviation'],
              event['competitions'][0]['competitors'][0]['score'],
              event['competitions'][0]['competitors'][1]['team']['abbreviation'],
event['competitions'][0]['competitors'][1]['score'])
```

outputs

```
1 2017 1 DAL 0 ARI 0
1 2017 2 CAR 0 HOU 0
1 2017 2 MIA 0 ATL 0
1 2017 2 BUF 0 MIN 0
1 2017 2 BAL 0 WSH 0
1 2017 2 NE 0 JAX 0
1 2017 2 CLE 0 NO 0
1 2017 2 GB 0 PHI 0
1 2017 2 CHI 0 DEN 0
1 2017 2 NYG 0 PIT 0
1 2017 2 CIN 0 TB 0
1 2017 2 KC 0 SF 0
...etc
```

**Comment by Kirkman** [comment]
As a long-term user of nflgame, to me one of the biggest annoyances is the need to manually edit `_CUR_SCHEDULE` or git pull in order to get schedule updates for postseason, or for a new season.

Is there not some way in code to get nflgame to detect when the season type has changed, and switch the `_CUR_SCHEDULE` url automatically?

**Comment by mrcartier** [comment]
Just tried to update schedule for 2017 & no luck...

cartier@cartier-VirtualBox:~/Documents/nflAPI/lib/python2.7/site-packages/nflgame$ python update_sched.py --year 2017
Last updated: 2017-08-10 15:27:08.076242
Updating (2017, PRE, 0)...
Updating (2017, PRE, 1)...
Updating (2017, PRE, 2)...
Updating (2017, PRE, 3)...
Updating (2017, PRE, 4)...
Updating (2017, REG, 1)...
Updating (2017, REG, 2)...
Updating (2017, REG, 3)...
Updating (2017, REG, 4)...
Updating (2017, REG, 5)...
Updating (2017, REG, 6)...
Updating (2017, REG, 7)...
Updating (2017, REG, 8)...
Updating (2017, REG, 9)...
Updating (2017, REG, 10)...
Updating (2017, REG, 11)...
Updating (2017, REG, 12)...
Updating (2017, REG, 13)...
Updating (2017, REG, 14)...
Updating (2017, REG, 15)...
Updating (2017, REG, 16)...
Updating (2017, REG, 17)...
Updating (2017, POST, 1)...
Updating (2017, POST, 2)...
Updating (2017, POST, 3)...
Updating (2017, POST, 4)...

But when trying to get 2017 season after updating

>>> import nflgame
>>> season = nflgame.games(2017)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cartier/Documents/nflAPI/lib/python2.7/site-packages/nflgame/__init__.py", line 229, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable

I'm certain live.py was using http://www.nfl.com/liveupdate/scorestrip/ss.xml for the URL & there's clearly data there... is it a must to use the database or did I leave something out?

**Comment by derek-adair** [comment]
no games will appear in nflgame.games() until they are completed.  That query is looking for regular season games by default.  If you want to see the completed pre-season games (AFTER running the command you did to update the schedule), try this...

s = nflgame.games(year=2017, kind="PRE")

If you want to return a list of games not played, i've found the best way is to use _search_schedule.

import nflgame
s = nflgame._search_schedule(year=2017)

**Comment by derek-adair** [comment]
Also I agree with @kirkman that the manual aspect of updating/maintaining schedules is... not desirable.  Personally I will be rigging up some kind of script to do this in my docker image... but it'd be rad to not even have to deal w/ that crap.
