### ISSUE TITLE
NCAAF Game Center

### ISSUE THREAD

**Issue by BobbySouzaEDA** [BurntSushi/nflgame#300]
Hi there, 

First off, this is amazing. The level of detail provided has helped tremendously. I use this data every day and I want to thank you for putting this together and keeping it afloat. 

This is not an issue but more of a question on whether this can be translated to NCAAF's Game Center (or if you have plans to do so)? The only reason I ask this here is because I'm hoping you may have some insight on whether it's similar/possible to pull the same data for college players? (particularly, **air yards per pass**)

Hope I'm not creating clutter and I'd appreciate any feedback.

Thank you!

**Comment by BurntSushi** [comment]
No. They are run by two completely different entities, and `nflgame` uses an undocumented JSON service from NFL.com. Sorry.
