### ISSUE TITLE
python 3.6 compatibility

### ISSUE THREAD

**Issue by shakewhat** [BurntSushi/nflgame#312]
Hello,

Are there plans to update nflgames to support Python 3.6, or possible work arounds? My employer is my only pv with data analysis tools installed(I'm only able to install python 3.6 also) and I was hoping to try this out before my drafts in a few weeks.

**Comment by shakewhat** [comment]
nvm I found a thread that covers this exactly.  Sorry!

**Comment by BurntSushi** [comment]
> Are there plans to update nflgames to support Python 3.6, or possible work arounds?

Not in the immediate future. Use Python 2.7.
