### ISSUE TITLE
missing httplib2

### ISSUE THREAD

**Issue by jspham** [BurntSushi/nflgame#314]
Hi - I tumbled upon this gem yesterday for a school project. while updating the player database, I am getting this error message when running nflgame-update-players script.

C:\Python27>python c:\python27\Scripts\nflgame-update-players
Traceback (most recent call last):
  File "c:\python27\Scripts\nflgame-update-players", line 3, in <module>
    import nflgame.update_players
  File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 51, in <module>
    import httplib2
ImportError: No module named httplib2

I installed nflgame using pip below: 

pip install nflgame
Requirement already satisfied: nflgame in c:\python27\lib\site-packages

any help would be appreciated!
thanks

**Comment by ochawkeye** [comment]
How did you install `nflgame`  if installed via `pip` it should have installed `httplib2` automatically.  If you installed it some other way it probably wouldn't have installed the dependencies but `pip install nflgame` sees that you already have the latest version of `nflgame`.

If you didn't use `pip` the first time around, try `pip install --upgrade --force-reinstall nflgame`.

**Comment by jspham** [comment]
that works!  thank you.

I am getting a socket timed out error:


C:\Python27>Python c:\Python27\Scripts\nflgame-update-players
Loading games for PRE 2017 week 2
Finding (profile id -> gsis id) mapping for players...
105/528 complete. (19.89%)Traceback (most recent call last):
  File "c:\Python27\Scripts\nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 386, in run
    for i, t in enumerate(pool.imap(fetch, players.items()), 1):
  File "C:\Python27\lib\multiprocessing\pool.py", line 626, in next
    raise value
socket.timeout: timed out

**Comment by BurntSushi** [comment]
@jspham It's either a problem with your Internet, or nfl.com is down. Probably the former.

**Comment by jspham** [comment]
i will keep trying  - thanks

is there anyway for me to donate to this project?

**Comment by BurntSushi** [comment]
@jspham 

> is there anyway for me to donate to this project?

No. If you really want to donate, I'd recommend donating to [the Wikimedia foundation](https://wikimediafoundation.org/wiki/Ways_to_Give) or [Rails Girls](https://railsgirlssummerofcode.org/campaign/).

**Comment by jspham** [comment]
Okay -  i will do that

**Comment by derek-adair** [comment]
good guy @BurntSushi ... damn yo.  I was just thinking about buying you a beer.  Iguess i'll donate to another foundation :)
