### ISSUE TITLE
data missing from players.json

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nflgame#318]
At some point, data in the players.json has gone missing.  As an example, Nick Novak is now missing Position, Status, and Team.

```
    "00-0023096": {
        "birthdate": "8/21/1981",
        "college": "Maryland",
        "first_name": "Nick",
        "full_name": "Nick Novak",
        "gsis_id": "00-0023096",
        "gsis_name": "N.Novak",
        "height": 72,
        "last_name": "Novak",
        "number": 8,
        "profile_id": 2506194,
        "profile_url": "http://www.nfl.com/player/nicknovak/2506194/profile",
        "weight": 200,
        "years_pro": 10
    },

```
I tried to do a `nfldb-update --player-interval 0` and that didn't fix the problem.  I then attempted `nflgame-update-players -- full-scan` but that is giving an error of:
```
`Loading players in games since 2009, this may take a while...
Traceback (most recent call last):
  File "/usr/local/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/update_players.py", line 358, in run
    for _, schedule in nflgame.sched.games.itervalues():
ValueError: too many values to unpack
`
```

Please let me know if some other ideas.

**Comment by mesee298** [comment]
Something I forgot to mention is it is  doesn't seem to be running the pulling new gsis_ids.  Maybe that isn't a big deal, but I've never seen that before.

```
Loading games for REG 2017 week 1
Downloading team rosters...
32/32 complete. (100.00%)
Done!

```

**Comment by cjsfj** [comment]
FWIW Nick Novak was cut by the Texans. So technically he is not on any team...

**Comment by mesee298** [comment]
ARGH!  Thanks @cjsfj

**Comment by Coop197823** [comment]
so I have noticed when I run the update_players.pyc utility it does not replace the existing players.json...
