### ISSUE TITLE
Player Update Failed

### ISSUE THREAD

**Issue by HvyOnEz** [BurntSushi/nflgame#322]
nflgame-update-players

Doesn't seem to have ended cleanly. Any Ideas???

Loading games for REG 2017 week 1
Finding (profile id -> gsis id) mapping for players...
2/2 complete. (100.00%)
Done!
Downloading team rosters...
32/32 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
157/157 complete. (100.00%)
Done!

There were some errors during the download. Usually this is a
result of an HTTP request timing out, which means the
resulting "players.json" file is probably missing some data.
An appropriate solution is to re-run the script until there
are no more errors (or when the errors are problems on 
NFL.com side.)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033923, K.Hunt)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033947, D.Wise)
-------------------------------------------------------------------------------
Could not get player info from roster row:

<tr class="even">
<td>72</td>
<td style="text-align:left"> <a href="/player/charleslenojr./2550169/profile">Leno, Charles, Jr.</a></td>
<td>OT</td>
<td>ACT</td>
<td> 6'3"</td>
<td>306</td>
<td>10/9/1991</td>
<td>4</td>
<td>Boise State</td></tr>

Exception:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nflgame/update_players.py", line 419, in run
    roster.append(meta_from_soup_row(team, row))
  File "/usr/lib/python2.7/site-packages/nflgame/update_players.py", line 179, in meta_from_soup_row
    last_name, first_name = map(lambda s: s.strip(), name.split(','))
ValueError: too many values to unpack

**Comment by brbeaird** [comment]
Yep, I get this, too.

**Comment by ochawkeye** [comment]
Splitting the string `Leno, Charles, Jr.` on its commas (`name.split(',')`) leaves you with 3 substrings.  `Leno`, `Charles`, and `Jr.`.  Since you can't unpack three things into two buckets you receive a `ValueError`.

Changing the file to something like #224 will fix your problem.

**Comment by HvyOnEz** [comment]
Thanks, I'll give it a try

**Comment by lark047** [comment]
I got this too before I changed my `update_players.py` with [#224](https://github.com/BurntSushi/nflgame/pull/224). Though I can run `nflgame-update-players` without error now, I am missing a lot of players. Is there some way to force update all players?

**Comment by HvyOnEz** [comment]
I updated the script to handle the Jr. issue, uninstalled nflGame and reinstalled directly from gitHub and the the updates ran smoothly... as for missing players, I haven't noticed anything out of the ordinary...
