### ISSUE TITLE
Can't read from 2017 games

### ISSUE THREAD

**Issue by stermi01** [BurntSushi/nflgame#335]
After managing to set my schedule up for 2017 games, I'm still having trouble reading 2017 regular season games. Getting the following error, just trying to get basic info that you had from issue #331  :

I updated nflgame and made sure to update the schedule as well as switch it back. Any idea?

Code:

import nflgame
import csv

games = nflgame.games(2017)
print len(games)

Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-8e57568beccf> in <module>()
      2 import csv
      3 
----> 4 games = nflgame.games(2017)
      5 print len(games)

C:\Program Files\Anaconda2\lib\site-packages\nflgame\__init__.pyc in games(year, week, home, away, kind, started)
    227     (as opposed to waiting for a 404 error from NFL.com).
    228     """
--> 229     return list(games_gen(year, week, home, away, kind, started))
    230 
    231 

TypeError: 'NoneType' object is not iterable

**Comment by stermi01** [comment]
had to add the following to the statement

games = nflgame.games(2017, kind = 'REG')

**Comment by ochawkeye** [comment]
Not sure why that would do anything different for you...`'REG'` is the default value for `kind`.
https://github.com/BurntSushi/nflgame/blob/master/nflgame/__init__.py#L192

**Comment by stermi01** [comment]
I'm not sure, It was something that ended up happening last year where I had trouble getting individual postseason games and since then I've had some problems, but that seemed to be the solution that worked.
