### ISSUE TITLE
2017 week 1-8 is missing

### ISSUE THREAD

**Issue by mrr-phys** [BurntSushi/nflgame#343]
Hi, I get this error:

TypeError                                 Traceback (most recent call last)
<ipython-input-89-d598f706ee5f> in <module>()
----> 1 games = nfl.games(2017,week=3)
      2 players = nfl.combine(games)

/Users/mrr/anaconda2/lib/python2.7/site-packages/nflgame/__init__.pyc in games(year, week, home, away, kind, started)
    227 def games_gen(year, week=None, home=None, away=None,
    228               kind='REG', started=False):
--> 229     """
    230     games returns a generator of all games matching the given criteria. Each
    231     game can then be queried for player statistics and information about

TypeError: 'NoneType' object is not iterable

**Comment by mrr-phys** [comment]
import nflgame
games = nflgame.games(2017)
print len(games)

> 1

**Comment by mtdiedrich** [comment]
ochawkeye's solution in [this thread](https://github.com/BurntSushi/nflgame/issues/331) solved the issue for me. Have a crack at it, if you haven't already.

**Comment by mrr-phys** [comment]
Thank you!
