### ISSUE TITLE
missing data for week 11 MIA @ TB

### ISSUE THREAD

**Issue by rjh336** [BurntSushi/nflgame#348]
when running the following code, I am missing week 11's game MIA at TB:
```
games = nflgame.games(2017, home='MIA', away='MIA')
for g in games:
    print g.nice_score()
```

the output is:

```MIA (19) at LAC (17)
MIA (6) at NYJ (20)
NO (20) at MIA (0)
TEN (10) at MIA (16)
MIA (20) at ATL (17)
NYJ (28) at MIA (31)
MIA (0) at BAL (40)
OAK (27) at MIA (24)
MIA (21) at CAR (45)
```
I tried updating the schedule per the following `python update_sched.py --year 2017` in the following directory **~/anaconda2/envs/nfl/lib/python2.7/site-packages/nflgame**, but the output has not changed. Not sure if it is pertinent, but is there any problem with using nflgame in a conda environment? If no, does anyone have suggestions?
thanks in advance.
@ochawkeye  
@BurntSushi

**Comment by ariannedee** [comment]
@rjh336 
Can you try the fix I suggested [here](https://github.com/BurntSushi/nflgame/issues/331#issuecomment-346203497)?

In `nflgame/live.py`, line 73 needs to be commented out and line 68 commented in.
Then you can run `update_sched.py` and it should pull in the right data.

I did that to get MIA vs TB in week 11.

**Comment by rjh336** [comment]
Thank you @ariannedee !!
