### ISSUE TITLE
Noob question re: pulling 2017 data

### ISSUE THREAD

**Issue by aggere1** [BurntSushi/nflgame#351]
after installing python and nflgame via pip without problems, I do this from a command prompt:
python
import nflgame
nflgame.combine_max_stats(nflgame.games(2017)).csv("c:\users\xxxxx\desktop\2017.csv")

with the above, and other variations, the csv is not saved to my desktop (file shows up in c:\users\xxxx directory) and only contains stats for one game rather than season to date.

what am I doing wrong that is resulting in only one week of game data to be in the csv file?

thank you.

**Comment by aggere1** [comment]
closing issue....I had to go to nflgame directory because I didnt have environment variable setup correctly and run python update_sched.py --year 2017 from that directory.

**Comment by derek-adair** [comment]
What can we do to alleviate the scheduling / data issues?

Looking at the issue history it should be very evident that something should be done to automatically keep the schedule up to date.  Juuuust about once a week i see someone posting that they "Dont have any games" or something like that...

Has anybody proposed a viable solution to keep data up-to-date?
