### ISSUE TITLE
Data Integrety Issues

### ISSUE THREAD

**Issue by derek-adair** [BurntSushi/nflgame#352]
I'm filing this issue because I see no concerted effort to alleviate the data pulling issues, in particular how update_schedule.py works, namely that it is not automatically up-to-date upon install.

Just glancing at the issue's, here are the ones filed because the data isn't automatically updated;

* #347 
* #331 
* #292 (kinda)
* #30 (related, whats the word on these explanations?)

And a WHOOOLE bunch of [closed issues](https://github.com/BurntSushi/nflgame/issues?q=is%3Aissue+missing+is%3Aclosed)

**What I would like to see:**

* nflgame automatically updates the schedule/data upon install
* An option for zero manual intervention, but this may be silly w/ nflgame.live
 
I'm sure this list will grow, i'm just not sure what else could be done to improve this, or at least prevent the initial confusion for people installing this for the first time.

Any thoughts?

**Comment by BurntSushi** [comment]
> because I see no concerted effort to alleviate the data pulling issues

There is no concerted effort to do _anything_. This project is basically unmaintained at this point because I don't have the time or interest to continue maintaining it. And yes, I should add a note to the README but haven't done so.

**Comment by derek-adair** [comment]
It's all good @BurntSushi, you should know we all adore your work.  This project has become a cornerstone for an app i've built so i'd like to help.

**Comment by derek-adair** [comment]
Before the next season I will need some fashion of updating schedule data automatically, so if you have any tips on how I may achieve this that'd be awesome.

**Comment by BurntSushi** [comment]
I don't have any specific ideas. I think it's just a matter of figuring out how to manage internal state ("what I know about the world at some particular time") with external state ("what I _could_ know about the world at some particular time"). And in particular, making sure you don't expend gratuitous resources in managing that state. For example, the player updating script goes through numerous heuristics to avoid sending a lot of additional HTTP requests to NFL.com. The initial crawl will send a lot, but future updates are incremental.

As a clear example, "updating the schedule" should not involve "sending dozens of HTTP requests to download the entire schedule for the past several years." That might seem obvious, but it's just an example. :)
