### ISSUE TITLE
Week 16 data?

### ISSUE THREAD

**Issue by joshbegley** [BurntSushi/nflgame#355]
Hi there—I've been using `nflgame` all season and it's been great. Thank you. Quick question: all the data from week 16 appears to be null. Any reason you think this might be?

I'm getting the following error on my usual script `TypeError: 'NoneType' object is not iterable`

Many thanks,
Josh

**Comment by lerxst** [comment]
I was running into a similar issue yesterday, but used the following `pip install` and it worked:
```
pip install git+https://github.com/BurntSushi/nflgame.git
```

**Comment by joshbegley** [comment]
Strange! Tried that, but it isn't working for me. If you happen to have a moment, could you run this and email me the output?

```
import nflgame

games = nflgame.games(2017, week=16)
plays = nflgame.combine_plays(games)
for p in plays:
    print p
```
All good if not! And thanks so much for the quick reply.

**Comment by djwessel** [comment]
I was able to get the week 16 data using the pip install listed above. Your script also output the expected plays for week 16.

**Comment by joshbegley** [comment]
Thanks, all. Closing the issue for now.
