### ISSUE TITLE
API Site down

### ISSUE THREAD

**Issue by lukegerhart** [BurntSushi/nflgame#359]
Not sure what the best place to ask this is, but is the API website down?

**Comment by ochawkeye** [comment]
API website?

**Comment by lukegerhart** [comment]
The API documentation http://pdoc.burntsushi.net/nflgame
Not sure if I'm missing something, but the link was up a few weeks ago.

**Comment by BurntSushi** [comment]
I switched hosting providers and don't plan on maintaining those API docs any more. If people want it, they can install pdoc (`pip install pdoc`) and generate the docs themselves.

Note that I've finally put up a notice that this project is unmaintained: https://github.com/BurntSushi/nflgame/commit/c9747ccb597d6c31f61e4002bc4bd9f45a05b064

**Comment by lukegerhart** [comment]
Thanks @BurntSushi

**Comment by ochawkeye** [comment]
![](https://media1.popsugar-assets.com/files/thumbor/DhxwtHHsvwlR_-EHxAxVSVN95ec/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2014/04/29/886/n/1922398/3e4e533c0eda5005_sonic-games-miley-cyrus-celebrities-851565/i/Sexy-Side-Eye-Cry.gif)

**Comment by BurntSushi** [comment]
@ochawkeye :-( I'm pretty sure that has been the reality for the past couple years anyway. About time it was officially acknowledged. :-)
