### ISSUE TITLE
Where to find variable information

### ISSUE THREAD

**Issue by wickedflow** [BurntSushi/nflgame#376]
Forgive me if this isn't an issue or my jargon may be wrong. 

I'm looking for information where I can find all the variables for players and games, like passing_att, and punting_yds. I found the stat types in the Wiki, but I'm not sure where to find the ones for games.

I also have this code that I need help with: 

for p in players.filter(p.passing_att>5):
    print(p, p.passing_att, p.passing_cmo, p.passing_tds, p.passing_int)

but i get the error: 
TypeError: filter() takes 1 positional argument but 2 were given

Any help is appreciated!

**Comment by BurntSushi** [comment]
Please consider reading the README before filing issues on a project:

![github-nflgame-unmaintained](https://user-images.githubusercontent.com/456674/65901130-8a2ef700-e385-11e9-8793-3b5040788e1b.png)
