### ISSUE TITLE
Player ESB IDs

### ISSUE THREAD

**Issue by mrcaseb** [BurntSushi/nflgame#379]
I am looking for a method to get some special NFL player information. To be precise, I want to find out what the player's corresponding esb id is via the gsis id. Or even better: I need the headshot url on nfl.com (which is built over the esb_id). If I understand this correctly, then you load the player data via the json file belonging to the package. Can you add esb_id or headshot url?
Or is there a method how we can access the NFL api directly? Because I believe I need the Person domain (see [https://api.nfl.com/docs/league/models/person/index.html](url))

**Comment by BurntSushi** [comment]
Before filing issues on a project, please consider reading the README first:

![unmaintained](https://user-images.githubusercontent.com/456674/77754430-b60ffa00-7001-11ea-954c-b70be2da3942.png)

**Comment by mrcaseb** [comment]
Actually nflgame-redux is redirecting to your repo on [https://pypi.org/project/nflgame-redux/](url) 
to report issues. Sorry for the inconvenience.
