### ISSUE TITLE
Anyway to discern a player's position?

### ISSUE THREAD

**Issue by gojonesy** [BurntSushi/nflgame#38]
Hello!

I hope this isn't a duplicate issue...

Is there anyway to determine a player's position? For instance, when returning a list of receiving leaders for a week, it would be nice to further filter that list to show only Tight Ends or Running Backs.

Love this API! Thanks for all of the hard work.

**Comment by hayntopdawg** [comment]
@ochawkeye or @BurntSushi the `.player` method uses current player data.  i.e. if the player is a free agent or is retired, his team and position values are `''`.  Is there a way to get the player's team and position for that set of game(s)?  I think I can probably extract the team, but I was hoping there would be an efficient method similar to the solution above.  Thank you for your assistance.
