### ISSUE TITLE
Schedule URL always uses PostSeason

### ISSUE THREAD

**Issue by weixiyen** [BurntSushi/nflgame#82]
In **nflgame.live**, there's this code below:

```
_CUR_SCHEDULE_URL = "http://www.nfl.com/liveupdate/scorestrip/ss.xml"
"""
Pinged infrequently to discover the current week number, year and week type.
The actual schedule of games is taken from the schedule module.
"""

_CUR_SCHEDULE_URL = "http://static.nfl.com/liveupdate/scorestrip/postseason/ss.xml"
"""
The URL for the XML schedule of the post season. This is only used
during the post season.

TODO: How do we know if it's the post season?
"""
```

Is there a plan to add post-season detection at some point?  

The main issue is I'd like to download the Regular season schedule for 2014 and it seems that this code actually won't allow it to happen.

**Comment by BurntSushi** [comment]
> It's been a year so maybe I'm a bit fuzzy, but I don't recall needing to swap _CUR_SCHEDULE_URL for regular -> postseason schedule creation.

*You* don't, but I do. :-) I've released a new updated with the switched URL and things should be back to normal now.
