### ISSUE TITLE
GSS_ID

### ISSUE THREAD

**Issue by rjhaz** [BurntSushi/nflgame#86]
Forgive me if this is somewhere I missed- it is NOT an issue with nflgame.  I find about 270 RB, QB, TE, WR, K, positions on NFL.com without a gss-id (or so says the player update program).  These are mostly new players in the league. I know it is up to the NFL to assigned them but I was wondering if anyone has experience from years past as to when they get assigned... people building their draft lists are missing new players like Manzeil since he has no gss-id (my program maps gss-id to RaysFFL playerid)... I can add code to put these players in my database but if the NFL generally assign a gss-id, say by the first game of the preseason (Sunday, 8/3), then I will just wait. 

Ray

**Comment by gullo** [comment]
Stumbled across this.  Appears to be occurring again this year.  Rookies have not been assigned a GSIS_ID, at least from the source I'm pulling from (Sleeper Apps API).  I see they are assigned if you look at the source code on NFL.com, but perhaps not through the JSON yet....Hopefully it fixes itself like in the years past.

**Comment by mickeelm** [comment]
@gullo this project is unmaintained/stale, please see the readme for the active fork.
